-- Banco de questões — lote 2 (12 CCP + 12 SAA, originais, com dicas).

insert into questions (cert_id, domain, prompt, choices, correct_choice_ids, explanation, difficulty, hint) values

-- ===================== CCP: Conceitos de Nuvem =====================
('ccp', 'Conceitos de Nuvem',
 'Uma empresa quer implantar sua aplicação em três continentes em questão de minutos. Qual característica da AWS torna isso possível?',
 '[{"id":"a","text":"Infraestrutura global com Regiões em todo o mundo"},{"id":"b","text":"AWS Outposts"},{"id":"c","text":"Planos de suporte Enterprise"},{"id":"d","text":"Amazon Lightsail"}]',
 '{a}',
 'A infraestrutura global (Regiões e AZs em todos os continentes) permite implantar globalmente em minutos — o benefício "go global in minutes". Outposts leva a AWS para o datacenter do cliente, o oposto do cenário.',
 'easy',
 'É um dos 6 benefícios da nuvem: "alcance global em minutos". O que torna isso fisicamente possível?'),

('ccp', 'Conceitos de Nuvem',
 'Qual termo descreve a capacidade de um sistema aumentar E diminuir recursos automaticamente conforme a demanda varia?',
 '[{"id":"a","text":"Tolerância a falhas"},{"id":"b","text":"Elasticidade"},{"id":"c","text":"Durabilidade"},{"id":"d","text":"Latência"}]',
 '{b}',
 'Elasticidade é ajustar recursos nas DUAS direções conforme a demanda. Tolerância a falhas é continuar operando com falhas; durabilidade é não perder dados.',
 'easy',
 'A palavra-chave é "aumentar E diminuir automaticamente". Um elástico estica e volta.'),

('ccp', 'Conceitos de Nuvem',
 'Uma consultoria precisa apresentar à diretoria um plano de adoção de nuvem cobrindo pessoas, governança e plataforma. Qual recurso da AWS orienta esse planejamento?',
 '[{"id":"a","text":"AWS Well-Architected Framework"},{"id":"b","text":"AWS Cloud Adoption Framework (CAF)"},{"id":"c","text":"AWS Trusted Advisor"},{"id":"d","text":"AWS Config"}]',
 '{b}',
 'O CAF organiza a adoção de nuvem em 6 perspectivas organizacionais (Negócio, Pessoas, Governança, Plataforma, Segurança, Operações). Well-Architected é sobre arquitetura de workloads, não sobre a organização.',
 'medium',
 '"Pessoas e governança" = transformação da ORGANIZAÇÃO, não de um workload específico.'),

-- ===================== CCP: Segurança e Conformidade =====================
('ccp', 'Segurança e Conformidade',
 'Qual prática protege o usuário root de uma conta AWS nova? (Escolha DUAS)',
 '[{"id":"a","text":"Ativar MFA no root"},{"id":"b","text":"Usar o root nas tarefas diárias"},{"id":"c","text":"Criar um usuário IAM administrador para o dia a dia"},{"id":"d","text":"Compartilhar a senha root com o time de TI"}]',
 '{a,c}',
 'Root: MFA ativado e uso reservado só a tarefas exclusivas (fechar conta, plano de suporte). O dia a dia é com usuário IAM/Identity Center. Compartilhar root é a pior prática possível.',
 'easy',
 'Root = cofre: tranca extra e uso raríssimo. Quem trabalha no dia a dia é outra identidade.'),

('ccp', 'Segurança e Conformidade',
 'Ao usar Amazon RDS, quem é responsável por aplicar patches no sistema operacional do servidor de banco de dados?',
 '[{"id":"a","text":"O cliente"},{"id":"b","text":"A AWS"},{"id":"c","text":"O fornecedor do banco (Oracle/MySQL)"},{"id":"d","text":"Responsabilidade compartilhada meio a meio"}]',
 '{b}',
 'RDS é serviço GERENCIADO: a AWS cuida do SO e da infraestrutura; o cliente cuida de dados, usuários e configurações de acesso. Em EC2 o patch do SO seria do cliente — essa fronteira é a pegadinha.',
 'medium',
 'Compare: em EC2 o SO é seu; em RDS, quem "aluga o banco pronto" não mexe no SO.'),

('ccp', 'Segurança e Conformidade',
 'Uma empresa precisa garantir que os dados de um bucket S3 estejam criptografados e que as chaves possam ser auditadas e rotacionadas. Quais serviços atendem? (Escolha DUAS)',
 '[{"id":"a","text":"AWS KMS"},{"id":"b","text":"Amazon GuardDuty"},{"id":"c","text":"Criptografia server-side do S3 (SSE-KMS)"},{"id":"d","text":"AWS Shield"}]',
 '{a,c}',
 'SSE-KMS criptografa os objetos usando chaves do KMS, que oferece auditoria (via CloudTrail) e rotação. GuardDuty detecta ameaças e Shield protege contra DDoS — nada a ver com criptografia.',
 'medium',
 'Criptografar + auditar/rotacionar CHAVES: um serviço aplica, outro gerencia as chaves.'),

-- ===================== CCP: Tecnologia e Serviços =====================
('ccp', 'Tecnologia e Serviços',
 'Uma aplicação web precisa distribuir tráfego entre várias instâncias EC2 saudáveis em duas AZs. Qual serviço faz isso?',
 '[{"id":"a","text":"Amazon CloudFront"},{"id":"b","text":"Elastic Load Balancing"},{"id":"c","text":"AWS Auto Scaling"},{"id":"d","text":"Amazon Route 53"}]',
 '{b}',
 'O ELB distribui tráfego entre alvos saudáveis em múltiplas AZs. Auto Scaling ajusta a QUANTIDADE de instâncias (os dois trabalham juntos); CloudFront é CDN; Route 53 é DNS.',
 'easy',
 '"Distribuir tráfego entre instâncias" é literalmente a função de um balanceador de carga.'),

('ccp', 'Tecnologia e Serviços',
 'Um site precisa de um banco NoSQL com latência de milissegundos e escala automática, sem administração de servidores. Qual serviço escolher?',
 '[{"id":"a","text":"Amazon RDS"},{"id":"b","text":"Amazon Redshift"},{"id":"c","text":"Amazon DynamoDB"},{"id":"d","text":"Amazon ElastiCache"}]',
 '{c}',
 'DynamoDB: NoSQL serverless, milissegundos em qualquer escala. RDS é relacional; Redshift é warehouse analítico; ElastiCache é cache (complemento, não banco principal).',
 'easy',
 '"NoSQL + serverless + milissegundos em qualquer escala" é o slogan de um serviço específico.'),

('ccp', 'Tecnologia e Serviços',
 'Uma empresa precisa executar as suas cargas AWS dentro do próprio datacenter por exigência de latência ultrabaixa local, mantendo as mesmas APIs da nuvem. Qual serviço atende?',
 '[{"id":"a","text":"AWS Outposts"},{"id":"b","text":"AWS Direct Connect"},{"id":"c","text":"Amazon CloudFront"},{"id":"d","text":"AWS Snowcone"}]',
 '{a}',
 'Outposts leva hardware e APIs da AWS para o datacenter do cliente (nuvem híbrida "de verdade"). Direct Connect é conectividade; CloudFront é CDN; Snowcone é transferência/edge portátil.',
 'medium',
 'A AWS "dentro de casa", com as mesmas APIs — é hardware da AWS instalado no SEU datacenter.'),

-- ===================== CCP: Cobrança, Preços e Suporte =====================
('ccp', 'Cobrança, Preços e Suporte',
 'Qual opção da AWS oferece orientação proativa e um Technical Account Manager (TAM) dedicado?',
 '[{"id":"a","text":"Plano de suporte Business"},{"id":"b","text":"Plano de suporte Enterprise"},{"id":"c","text":"AWS IQ"},{"id":"d","text":"AWS Trusted Advisor"}]',
 '{b}',
 'TAM dedicado é exclusividade do plano Enterprise. Business tem 24/7 e Trusted Advisor completo, mas sem TAM (Enterprise On-Ramp tem POOL de TAMs, não dedicado).',
 'easy',
 'TAM DEDICADO só existe no plano mais caro de todos.'),

('ccp', 'Cobrança, Preços e Suporte',
 'Que tipo de transferência de dados é normalmente GRATUITA na AWS? (Escolha DUAS)',
 '[{"id":"a","text":"Entrada de dados da internet para a AWS (ingress)"},{"id":"b","text":"Saída de dados da AWS para a internet (egress)"},{"id":"c","text":"Transferência entre AZs diferentes"},{"id":"d","text":"Transferência entre EC2 e S3 na mesma Região"}]',
 '{a,d}',
 'Ingress é grátis, e tráfego entre serviços na mesma Região (EC2→S3) em geral também. Egress para a internet e tráfego entre AZs/Regiões são cobrados — as maiores surpresas na fatura.',
 'medium',
 'Entrar na AWS é grátis; SAIR custa. Dentro da mesma região entre serviços, geralmente livre.'),

('ccp', 'Cobrança, Preços e Suporte',
 'Uma equipe quer identificar quais serviços mais cresceram na fatura nos últimos 6 meses e projetar os próximos 3. Qual ferramenta usar?',
 '[{"id":"a","text":"AWS Pricing Calculator"},{"id":"b","text":"AWS Cost Explorer"},{"id":"c","text":"AWS Artifact"},{"id":"d","text":"AWS Budgets"}]',
 '{b}',
 'Cost Explorer analisa o histórico com gráficos por serviço e faz previsão (forecast). Calculator estima cargas NOVAS; Budgets alerta sobre limites; Artifact é compliance.',
 'easy',
 'Passado + tendência futura da fatura = a ferramenta de ANÁLISE, não a de estimativa nem a de alerta.'),

-- ===================== SAA: Arquiteturas Seguras =====================
('saa', 'Arquiteturas Seguras',
 'Uma API precisa autenticar usuários finais de um aplicativo móvel com login social (Google/Apple) e emitir tokens. Qual serviço usar?',
 '[{"id":"a","text":"IAM Identity Center"},{"id":"b","text":"Amazon Cognito User Pools"},{"id":"c","text":"AWS STS diretamente"},{"id":"d","text":"Usuários IAM para cada cliente"}]',
 '{b}',
 'Cognito User Pools autentica usuários FINAIS de aplicações (com federação social) e emite tokens JWT. IAM/Identity Center são para quem OPERA a AWS — nunca crie usuários IAM para clientes de app.',
 'medium',
 'Usuários DO SEU APP ≠ usuários DA SUA CONTA AWS. Existe um serviço específico para os primeiros.'),

('saa', 'Arquiteturas Seguras',
 'Uma empresa precisa que TODAS as suas contas AWS sejam impedidas de criar recursos fora das regiões sa-east-1 e us-east-1. Qual é a forma mais eficaz?',
 '[{"id":"a","text":"Política IAM em cada usuário de cada conta"},{"id":"b","text":"SCP no nível da organização negando outras regiões"},{"id":"c","text":"AWS Config com auto-remediação"},{"id":"d","text":"Instruções por escrito para os times"}]',
 '{b}',
 'SCPs aplicam um teto de permissões a TODAS as contas da organização de uma vez — nem administradores das contas-membro escapam. IAM por usuário não escala e Config remedia DEPOIS do fato.',
 'medium',
 'Para valer para TODAS as contas de uma vez, o controle precisa vir de cima (da organização).'),

('saa', 'Arquiteturas Seguras',
 'Objetos de um bucket S3 devem ser acessíveis apenas via CloudFront, nunca diretamente. Qual é a configuração correta?',
 '[{"id":"a","text":"Bucket público com CloudFront na frente"},{"id":"b","text":"Origin Access Control (OAC) + bucket policy permitindo só o CloudFront"},{"id":"c","text":"Presigned URLs geradas manualmente"},{"id":"d","text":"Security group no bucket S3"}]',
 '{b}',
 'OAC permite que o CloudFront assine as requisições à origem; a bucket policy autoriza somente o serviço CloudFront. Bucket continua privado. S3 não tem security group — alternativa impossível.',
 'medium',
 'O bucket fica FECHADO e a política só abre para um "carteiro" específico assinado.'),

-- ===================== SAA: Arquiteturas Resilientes =====================
('saa', 'Arquiteturas Resilientes',
 'Um sistema de processamento de imagens usa SQS. Algumas mensagens malformadas causam falhas repetidas e voltam para a fila infinitamente, desperdiçando processamento. Qual é a correção?',
 '[{"id":"a","text":"Aumentar o visibility timeout"},{"id":"b","text":"Configurar uma dead-letter queue com maxReceiveCount"},{"id":"c","text":"Migrar para SQS FIFO"},{"id":"d","text":"Aumentar a retenção da fila"}]',
 '{b}',
 'A DLQ captura mensagens que falharam N vezes (maxReceiveCount), tirando-as do ciclo e preservando-as para análise. Visibility timeout maior só atrasa o loop; FIFO não resolve mensagens malformadas.',
 'medium',
 'Mensagem "envenenada" precisa de um destino para onde ir depois de N tentativas.'),

('saa', 'Arquiteturas Resilientes',
 'Uma aplicação stateful guarda sessões na memória das instâncias EC2, impedindo o Auto Scaling de remover instâncias sem deslogar usuários. Qual mudança viabiliza o scale-in seguro?',
 '[{"id":"a","text":"Sticky sessions no ALB para sempre"},{"id":"b","text":"Externalizar sessões para ElastiCache ou DynamoDB"},{"id":"c","text":"Desativar o scale-in"},{"id":"d","text":"Instâncias maiores"}]',
 '{b}',
 'Sessões externas (ElastiCache/DynamoDB) tornam as instâncias stateless — qualquer uma atende qualquer usuário e pode ser removida sem impacto. Sticky sessions só adia o problema; desativar scale-in desperdiça dinheiro.',
 'medium',
 'O problema é o estado DENTRO da instância. Tire-o de lá e as instâncias viram gado, não bicho de estimação.'),

('saa', 'Arquiteturas Resilientes',
 'Uma aplicação crítica roda em uma única região. A empresa quer failover automático de DNS para uma região secundária se os health checks falharem. O que configurar?',
 '[{"id":"a","text":"Route 53 com política de roteamento failover + health checks"},{"id":"b","text":"CloudFront com múltiplas origens"},{"id":"c","text":"Um Network Load Balancer entre regiões"},{"id":"d","text":"VPC Peering entre as regiões"}]',
 '{a}',
 'Route 53 failover routing monitora o endpoint primário via health check e responde com o secundário quando ele falha. ELB não atravessa regiões; peering é rede, não DNS.',
 'easy',
 'A "virada de chave" entre regiões acontece na camada de DNS, com monitoração de saúde.'),

-- ===================== SAA: Arquiteturas de Alta Performance =====================
('saa', 'Arquiteturas de Alta Performance',
 'Um job de análise em lote roda por 4 horas todas as noites e não pode passar de 6 horas. Qual opção de computação equilibra custo e requisito?',
 '[{"id":"a","text":"AWS Lambda"},{"id":"b","text":"Fargate ou EC2 Spot com AWS Batch e retry"},{"id":"c","text":"EC2 On-Demand 24/7"},{"id":"d","text":"Elastic Beanstalk"}]',
 '{b}',
 'Lambda estoura em 15 min. Batch com Spot (ou Fargate) roda horas com grande economia; se o Spot for interrompido, o retry conclui dentro da janela de 6h. Instância 24/7 desperdiça 20h/dia.',
 'hard',
 'Elimine primeiro pelo limite de 15 minutos; depois otimize custo para um job noturno interrompível.'),

('saa', 'Arquiteturas de Alta Performance',
 'Consultas repetidas e idênticas ao RDS estão elevando a latência das páginas de um portal. Qual solução reduz a latência SEM aumentar a instância do banco?',
 '[{"id":"a","text":"ElastiCache na frente do RDS (cache-aside)"},{"id":"b","text":"Multi-AZ"},{"id":"c","text":"Migrar para Redshift"},{"id":"d","text":"Snapshot diário"}]',
 '{a}',
 'Cache-aside com ElastiCache serve as consultas repetidas da memória, aliviando o banco. Multi-AZ é disponibilidade (a standby nem atende leitura); Redshift é analítico.',
 'easy',
 'Mesmas perguntas repetidas merecem respostas guardadas na memória, não idas ao banco.'),

('saa', 'Arquiteturas de Alta Performance',
 'Um site global serve imagens pesadas hospedadas no S3 em us-east-1. Usuários da Ásia reclamam de lentidão. Qual solução melhora a experiência com MENOR esforço?',
 '[{"id":"a","text":"Replicar o bucket para 5 regiões"},{"id":"b","text":"CloudFront com o bucket como origem"},{"id":"c","text":"Instâncias EC2 na Ásia servindo as imagens"},{"id":"d","text":"S3 Transfer Acceleration"}]',
 '{b}',
 'CloudFront cacheia as imagens nas edge locations perto dos usuários — uma distribuição resolve o mundo todo. Replicação multi-região funciona mas é mais cara/complexa; Transfer Acceleration otimiza UPLOADS.',
 'easy',
 'Conteúdo estático global = cache perto do usuário, não cópias do dado inteiro.'),

-- ===================== SAA: Custo Otimizado =====================
('saa', 'Arquiteturas com Custo Otimizado',
 'Instâncias EC2 de produção rodam 24/7 há um ano com uso constante, e a previsão é manter por mais 3 anos. O CFO quer o MAIOR desconto possível sem risco de interrupção. O que comprar?',
 '[{"id":"a","text":"Spot Instances"},{"id":"b","text":"Savings Plans/Reserved de 3 anos com pagamento antecipado (all upfront)"},{"id":"c","text":"On-Demand com tags"},{"id":"d","text":"Dedicated Hosts"}]',
 '{b}',
 'Compromisso de 3 anos com all upfront maximiza o desconto (até ~72%) sem risco de interrupção. Spot daria mais desconto mas pode ser interrompido — inaceitável para produção crítica.',
 'easy',
 '"Sem risco de interrupção" elimina a opção mais barata. Depois, quanto maior o compromisso, maior o desconto.'),

('saa', 'Arquiteturas com Custo Otimizado',
 'Um bucket com 200 TB de dados de acesso imprevisível gera custos altos. Alguns objetos são acessados diariamente, outros ficam meses sem acesso. Qual classe minimiza custo sem impacto de latência?',
 '[{"id":"a","text":"S3 Standard-IA para tudo"},{"id":"b","text":"S3 Intelligent-Tiering"},{"id":"c","text":"S3 Glacier Deep Archive"},{"id":"d","text":"S3 One Zone-IA"}]',
 '{b}',
 'Intelligent-Tiering move cada objeto entre camadas conforme o acesso real, sem taxa de recuperação nem impacto de latência — ideal para padrão DESCONHECIDO/imprevisível. IA cobraria recuperação dos objetos quentes; Glacier tem latência.',
 'medium',
 'Padrão de acesso IMPREVISÍVEL tem uma classe feita sob medida, com "camadas inteligentes".'),

('saa', 'Arquiteturas com Custo Otimizado',
 'A fatura mostra custo alto de NAT Gateway. A análise revela que 90% do tráfego é de instâncias privadas baixando objetos do S3 na mesma região. Como reduzir drasticamente esse custo?',
 '[{"id":"a","text":"Criar um Gateway VPC Endpoint para o S3 e rotear por ele"},{"id":"b","text":"Adicionar um segundo NAT Gateway"},{"id":"c","text":"Trocar NAT Gateway por NAT Instance"},{"id":"d","text":"Comprimir os objetos do S3"}]',
 '{a}',
 'Gateway Endpoint para S3 é gratuito e tira o tráfego S3 do NAT (que cobra por GB processado). Segundo NAT DOBRA o custo; NAT instance economiza pouco e cria gargalo.',
 'medium',
 '90% do custo é tráfego para um serviço que tem endpoint GRATUITO dentro da VPC.')

on conflict do nothing;
