-- Banco de questões — lote 3 (12 CCP + 12 SAA).

insert into questions (cert_id, domain, prompt, choices, correct_choice_ids, explanation, difficulty, hint) values

-- ===================== CCP: Conceitos de Nuvem =====================
('ccp', 'Conceitos de Nuvem',
 'Uma empresa mantém parte dos sistemas no datacenter próprio e parte na AWS, conectados por VPN. Como esse modelo de implantação é chamado?',
 '[{"id":"a","text":"Nuvem pública"},{"id":"b","text":"Nuvem híbrida"},{"id":"c","text":"Multi-cloud"},{"id":"d","text":"Nuvem privada"}]',
 '{b}',
 'Parte on-premises + parte na nuvem, integradas = nuvem híbrida. Multi-cloud seria usar dois provedores de nuvem diferentes.',
 'easy',
 'Metade em casa, metade na nuvem, conversando entre si — o nome descreve a mistura.'),

('ccp', 'Conceitos de Nuvem',
 'Qual das opções é um exemplo de PaaS (Plataforma como Serviço) na AWS?',
 '[{"id":"a","text":"Amazon EC2"},{"id":"b","text":"AWS Elastic Beanstalk"},{"id":"c","text":"Amazon S3"},{"id":"d","text":"AWS Outposts"}]',
 '{b}',
 'No Beanstalk você entrega o CÓDIGO e a plataforma provisiona e gerencia a infraestrutura — a definição de PaaS. EC2 é IaaS (você gerencia o SO).',
 'medium',
 'PaaS = você traz só o código. Qual serviço aceita um .zip da aplicação e cuida do resto?'),

('ccp', 'Conceitos de Nuvem',
 'Por que a AWS consegue oferecer preços menores do que datacenters próprios para a maioria das empresas?',
 '[{"id":"a","text":"Economia de escala: compra e opera infraestrutura para milhões de clientes"},{"id":"b","text":"Subsídio governamental"},{"id":"c","text":"Hardware de qualidade inferior"},{"id":"d","text":"Contratos obrigatórios de longo prazo"}]',
 '{a}',
 'A agregação de demanda de milhões de clientes gera economia de escala repassada nos preços — um dos 6 benefícios. Não há contratos obrigatórios (pay-as-you-go).',
 'easy',
 'Comprar servidores por milhão sai mais barato por unidade — e o desconto é repassado.'),

-- ===================== CCP: Segurança e Conformidade =====================
('ccp', 'Segurança e Conformidade',
 'Um analista precisa descobrir se buckets S3 da empresa contêm dados pessoais identificáveis (PII) expostos. Qual serviço automatiza essa descoberta?',
 '[{"id":"a","text":"Amazon Inspector"},{"id":"b","text":"Amazon Macie"},{"id":"c","text":"AWS WAF"},{"id":"d","text":"AWS CloudTrail"}]',
 '{b}',
 'Macie usa ML para descobrir e classificar dados sensíveis (PII) em S3. Inspector procura vulnerabilidades em EC2/ECR; WAF filtra tráfego web.',
 'easy',
 'PII + S3 + machine learning = um serviço com nome de detetive.'),

('ccp', 'Segurança e Conformidade',
 'Qual serviço detecta atividades anômalas na conta, como chamadas de API incomuns ou instâncias minerando criptomoedas?',
 '[{"id":"a","text":"Amazon GuardDuty"},{"id":"b","text":"AWS Artifact"},{"id":"c","text":"AWS Certificate Manager"},{"id":"d","text":"Amazon Macie"}]',
 '{a}',
 'GuardDuty analisa CloudTrail, VPC Flow Logs e DNS com inteligência de ameaças para detectar comportamento malicioso. Macie é específico para dados sensíveis no S3.',
 'easy',
 'O "guarda" da conta que observa comportamento estranho continuamente.'),

('ccp', 'Segurança e Conformidade',
 'Uma política IAM tem um Allow para s3:* e outra política aplicável tem Deny explícito para s3:DeleteObject. O usuário tenta deletar um objeto. O que acontece?',
 '[{"id":"a","text":"A ação é permitida porque o Allow veio primeiro"},{"id":"b","text":"A ação é negada: Deny explícito sempre vence"},{"id":"c","text":"Depende da ordem de criação das políticas"},{"id":"d","text":"O IAM pede confirmação ao usuário"}]',
 '{b}',
 'Na avaliação do IAM, um Deny explícito vence qualquer Allow, sempre. Ordem de criação é irrelevante.',
 'medium',
 'Na dúvida entre um "sim" e um "NÃO explícito", o IAM sempre fica com o não.'),

-- ===================== CCP: Tecnologia e Serviços =====================
('ccp', 'Tecnologia e Serviços',
 'Uma empresa quer criar e gerenciar sua infraestrutura AWS como código, de forma repetível entre contas. Qual serviço usar?',
 '[{"id":"a","text":"AWS CloudFormation"},{"id":"b","text":"AWS CloudShell"},{"id":"c","text":"Amazon CloudWatch"},{"id":"d","text":"AWS Systems Manager"}]',
 '{a}',
 'CloudFormation define infraestrutura em templates (JSON/YAML) e provisiona de forma idêntica quantas vezes precisar. CloudShell é um terminal; CloudWatch monitora.',
 'easy',
 '"Infraestrutura como código" tem um serviço dedicado cujo nome fala em "formação".'),

('ccp', 'Tecnologia e Serviços',
 'Qual serviço permite consultar dados armazenados no S3 usando SQL padrão, sem provisionar servidores?',
 '[{"id":"a","text":"Amazon RDS"},{"id":"b","text":"Amazon Athena"},{"id":"c","text":"Amazon Neptune"},{"id":"d","text":"AWS Glue"}]',
 '{b}',
 'Athena executa SQL diretamente sobre arquivos no S3, cobrando por consulta — serverless. Glue prepara/transforma dados (ETL); RDS exige carregar em banco.',
 'easy',
 'SQL direto nos arquivos do S3, pagando por consulta — nome de deusa grega.'),

('ccp', 'Tecnologia e Serviços',
 'Um e-commerce precisa enviar e-mails de confirmação, SMS e notificações push quando um pedido é aprovado, tudo a partir de um único evento. Qual serviço facilita isso?',
 '[{"id":"a","text":"Amazon SQS"},{"id":"b","text":"Amazon SNS"},{"id":"c","text":"AWS Batch"},{"id":"d","text":"Amazon Connect"}]',
 '{b}',
 'SNS é pub/sub: um evento publicado chega a vários assinantes (e-mail, SMS, push, filas...). SQS é fila para UM grupo consumidor processar.',
 'easy',
 'Um aviso, muitos destinatários de tipos diferentes — é notificação, não fila.'),

-- ===================== CCP: Cobrança, Preços e Suporte =====================
('ccp', 'Cobrança, Preços e Suporte',
 'Uma startup precisa dividir a fatura AWS por projeto para saber quanto cada produto custa. Qual mecanismo permite isso?',
 '[{"id":"a","text":"Criar uma conta root para cada projeto"},{"id":"b","text":"Tags de alocação de custo nos recursos"},{"id":"c","text":"AWS Artifact"},{"id":"d","text":"Alterar o plano de suporte"}]',
 '{b}',
 'Tags de alocação de custo (ex: projeto=loja) permitem filtrar e agrupar custos no Cost Explorer/CUR. Contas separadas também funcionam, mas "uma root por projeto" está errado conceitualmente.',
 'easy',
 'Etiquetar cada recurso com o nome do projeto e filtrar a fatura por etiqueta.'),

('ccp', 'Cobrança, Preços e Suporte',
 'O que o AWS Free Tier "always free" (sempre gratuito) inclui?',
 '[{"id":"a","text":"750 horas/mês de EC2 t2.micro para sempre"},{"id":"b","text":"1 milhão de requisições AWS Lambda por mês"},{"id":"c","text":"100 GB de S3 Standard para sempre"},{"id":"d","text":"Um TAM dedicado"}]',
 '{b}',
 'Lambda tem 1M de requisições/mês SEMPRE grátis. EC2 750h/mês e S3 5 GB valem apenas nos primeiros 12 meses (não são "always free").',
 'medium',
 'Cuidado com a diferença entre "12 meses grátis" e "sempre grátis". Serverless costuma estar no segundo grupo.'),

('ccp', 'Cobrança, Preços e Suporte',
 'Qual serviço verifica sua conta contra boas práticas de custo, performance, segurança, tolerância a falhas e limites de serviço?',
 '[{"id":"a","text":"AWS Trusted Advisor"},{"id":"b","text":"AWS Config"},{"id":"c","text":"Amazon Inspector"},{"id":"d","text":"AWS Health Dashboard"}]',
 '{a}',
 'Trusted Advisor faz verificações nos 5 pilares (custo, performance, segurança, tolerância a falhas, limites). Verificações completas exigem plano Business+.',
 'easy',
 'O "conselheiro de confiança" da conta, com 5 categorias de recomendações.'),

-- ===================== SAA: Arquiteturas Seguras =====================
('saa', 'Arquiteturas Seguras',
 'Uma aplicação em EC2 precisa chamar APIs da AWS. O time de segurança proíbe chaves de acesso em arquivos de configuração. Além de usar roles, como garantir que somente chamadas da VPC corporativa alcancem o S3?',
 '[{"id":"a","text":"Bucket policy com condição aws:SourceVpce apontando para o VPC Endpoint"},{"id":"b","text":"Tornar o bucket público apenas em horário comercial"},{"id":"c","text":"NACL no bucket"},{"id":"d","text":"Trocar as chaves semanalmente"}]',
 '{a}',
 'A condição aws:SourceVpce na bucket policy restringe o acesso a requisições vindas do VPC Endpoint específico — rede + identidade em camadas. NACL não se aplica a buckets.',
 'hard',
 'A bucket policy aceita CONDIÇÕES — inclusive "só aceite tráfego vindo deste endpoint da minha VPC".'),

('saa', 'Arquiteturas Seguras',
 'Um banco de dados RDS deve ter as credenciais rotacionadas a cada 30 dias e injetadas na aplicação sem constar em variáveis de ambiente em texto claro. Qual arquitetura atende?',
 '[{"id":"a","text":"Secrets Manager com rotação automática; a aplicação busca o segredo em runtime via SDK"},{"id":"b","text":"Senha fixa forte definida uma única vez"},{"id":"c","text":"Arquivo .env criptografado no repositório git"},{"id":"d","text":"Senha no user data da instância"}]',
 '{a}',
 'Secrets Manager rotaciona automaticamente e a aplicação lê o valor atual em runtime (com cache). Git e user data são vazamentos clássicos; senha fixa viola o requisito de rotação.',
 'medium',
 'O segredo deve morar num cofre com rotação nativa, e a aplicação pergunta ao cofre na hora de usar.'),

('saa', 'Arquiteturas Seguras',
 'Auditoria exige que TODAS as chamadas de API em TODAS as regiões da conta sejam registradas e que os logs sejam à prova de adulteração. O que configurar?',
 '[{"id":"a","text":"CloudTrail multi-região com log file validation, entregando em bucket S3 com MFA Delete"},{"id":"b","text":"CloudWatch Logs com retenção de 7 dias"},{"id":"c","text":"VPC Flow Logs em todas as VPCs"},{"id":"d","text":"AWS Config em uma região"}]',
 '{a}',
 'CloudTrail multi-região captura todas as chamadas; log file validation gera hash para detectar adulteração; S3 com proteções (MFA Delete/Object Lock) blinda os arquivos. Flow Logs são rede, não API.',
 'medium',
 'Chamadas de API = CloudTrail. "À prova de adulteração" pede a validação de integridade dos arquivos.'),

-- ===================== SAA: Arquiteturas Resilientes =====================
('saa', 'Arquiteturas Resilientes',
 'Um processamento crítico consome mensagens de uma fila SQS. Durante deploys, mensagens processadas pela metade voltam à fila e são processadas DUAS vezes, duplicando cobranças de clientes. Qual é a melhor solução?',
 '[{"id":"a","text":"Tornar o processamento idempotente (verificar se o pedido já foi processado)"},{"id":"b","text":"Aumentar o visibility timeout para 12 horas"},{"id":"c","text":"Reduzir o número de consumidores"},{"id":"d","text":"Usar long polling"}]',
 '{a}',
 'SQS Standard entrega "pelo menos uma vez" — duplicatas são esperadas por design. Consumidores idempotentes (checar ID do pedido antes de cobrar) são a solução correta. Timeout de 12h só atrasa reprocessamento legítimo.',
 'hard',
 'A garantia do SQS Standard é "PELO MENOS uma vez". Se duplicar é inevitável, o consumidor precisa saber reconhecer repetição.'),

('saa', 'Arquiteturas Resilientes',
 'Uma aplicação usa EBS para dados críticos. O RPO exigido é de 1 hora e os dados devem sobreviver à perda da AZ. Qual é a solução mais simples?',
 '[{"id":"a","text":"Snapshots automáticos do EBS a cada hora (Data Lifecycle Manager)"},{"id":"b","text":"RAID 1 entre dois volumes na mesma AZ"},{"id":"c","text":"Aumentar o tamanho do volume"},{"id":"d","text":"io2 com mais IOPS"}]',
 '{a}',
 'Snapshots são incrementais, armazenados no S3 (multi-AZ por natureza) e agendáveis via DLM — RPO de 1h atendido. RAID na mesma AZ morre junto com a AZ.',
 'medium',
 'EBS vive em UMA AZ; a cópia que sobrevive à AZ é o snapshot (que mora no S3). Basta agendar de hora em hora.'),

('saa', 'Arquiteturas Resilientes',
 'Um workload usa 10 instâncias idênticas atrás de um ALB. A empresa quer garantir que a falha de um único rack físico não derrube várias instâncias de uma vez. O que usar?',
 '[{"id":"a","text":"Spread placement group"},{"id":"b","text":"Cluster placement group"},{"id":"c","text":"Instâncias maiores"},{"id":"d","text":"Partition placement group com 1 partição"}]',
 '{a}',
 'Spread placement group coloca cada instância em hardware distinto (máx. 7 por AZ — com 2 AZs, cobre as 10). Cluster faz o OPOSTO (mesmo rack, para latência).',
 'medium',
 'Você quer ESPALHAR as instâncias por racks diferentes — o nome do placement group é literal.'),

-- ===================== SAA: Arquiteturas de Alta Performance =====================
('saa', 'Arquiteturas de Alta Performance',
 'Uma API serverless sofre com cold starts que violam o SLA de latência p99. Qual solução elimina o problema mantendo a arquitetura?',
 '[{"id":"a","text":"Provisioned concurrency nas funções Lambda críticas"},{"id":"b","text":"Migrar tudo para EC2"},{"id":"c","text":"Aumentar o timeout da função"},{"id":"d","text":"Reduzir a memória da função"}]',
 '{a}',
 'Provisioned concurrency mantém ambientes de execução pré-aquecidos — sem cold start. Timeout não afeta inicialização; menos memória PIORA (CPU proporcional).',
 'medium',
 'Existe uma forma de pagar para manter N ambientes da Lambda sempre "quentes".'),

('saa', 'Arquiteturas de Alta Performance',
 'Um jogo mobile grava placares em uma tabela DynamoDB. Nos horários de pico, escritas são rejeitadas (throttling) mesmo com auto scaling. O padrão de acesso concentra tudo na partition key do dia atual. Qual é a correção?',
 '[{"id":"a","text":"Adicionar sufixo aleatório/hash à partition key para distribuir as escritas (write sharding)"},{"id":"b","text":"Aumentar o tamanho dos itens"},{"id":"c","text":"Trocar para modo provisionado com menos capacidade"},{"id":"d","text":"Criar uma GSI com a mesma chave"}]',
 '{a}',
 'Hot partition: todas as escritas na MESMA partition key estouram o limite por partição, não a capacidade da tabela. Write sharding (dia#1..dia#N) distribui a carga. GSI com a mesma chave herda o problema.',
 'hard',
 'O gargalo não é a tabela, é UMA partição quente. A solução espalha a chave em N pedaços.'),

('saa', 'Arquiteturas de Alta Performance',
 'Arquivos de vídeo de 500 MB são enviados por usuários de vários continentes para um bucket S3 em us-east-1. Os uploads falham com frequência em conexões instáveis. Quais práticas melhoram a confiabilidade e a velocidade? (Escolha DUAS)',
 '[{"id":"a","text":"Multipart upload"},{"id":"b","text":"S3 Transfer Acceleration"},{"id":"c","text":"Compactar em um único ZIP de 10 GB"},{"id":"d","text":"Reduzir o timeout do client"}]',
 '{a,b}',
 'Multipart divide o arquivo em partes com retry independente (resiliência); Transfer Acceleration usa as edge locations para encurtar a rota global (velocidade). ZIP maior piora; timeout menor derruba mais.',
 'medium',
 'Dois problemas, duas soluções: partes recuperáveis para a instabilidade + rota pela borda para a distância.'),

-- ===================== SAA: Custo Otimizado =====================
('saa', 'Arquiteturas com Custo Otimizado',
 'Um cluster de análise processa dados 2h por dia em horário flexível. A carga tolera interrupções e reinícios. Qual estratégia de compra minimiza o custo?',
 '[{"id":"a","text":"Spot Instances"},{"id":"b","text":"Reserved Instances de 3 anos"},{"id":"c","text":"On-Demand"},{"id":"d","text":"Dedicated Hosts"}]',
 '{a}',
 'Tolerância a interrupção + horário flexível + poucas horas/dia = cenário perfeito de Spot (até 90% de desconto). Reservar 24/7 por 3 anos para usar 2h/dia é desperdício.',
 'easy',
 'Interrompível + flexível = o desconto máximo da AWS, com a contrapartida que este workload aceita.'),

('saa', 'Arquiteturas com Custo Otimizado',
 'O tráfego de saída (egress) do ALB para usuários finais domina os custos de uma aplicação de mídia. Qual mudança reduz esse custo?',
 '[{"id":"a","text":"CloudFront na frente (egress via CDN é mais barato e o cache reduz origem)"},{"id":"b","text":"Mover para uma região mais cara"},{"id":"c","text":"Trocar ALB por NLB"},{"id":"d","text":"Aumentar as instâncias"}]',
 '{a}',
 'CloudFront tem preço de saída menor que o egress direto e o cache elimina grande parte das idas à origem. Trocar o tipo de balanceador não muda o custo de transferência.',
 'medium',
 'Servir da borda com cache é mais barato do que servir tudo da origem — em dobro (menos GB e GB mais barato).'),

('saa', 'Arquiteturas com Custo Otimizado',
 'Uma empresa tem 40 contas AWS e quer maximizar descontos de Savings Plans comprados centralizadamente. O que garante que o desconto beneficie todas as contas?',
 '[{"id":"a","text":"Consolidated billing no AWS Organizations com compartilhamento de descontos ativado"},{"id":"b","text":"Comprar Savings Plans em cada conta separadamente"},{"id":"c","text":"Usar apenas uma conta gigante para tudo"},{"id":"d","text":"Tags de custo"}]',
 '{a}',
 'Com fatura consolidada, Savings Plans/RIs comprados em qualquer conta (idealmente na de pagamento) aplicam o desconto ao uso agregado de toda a organização. Uma conta única sacrifica isolamento.',
 'medium',
 'Organizations não só soma a fatura — descontos de compromisso fluem entre as contas da organização.')

on conflict do nothing;
