-- CCP: expansão para o número oficial do exame (+30, distribuição por peso de domínio).

insert into questions (cert_id, domain, prompt, choices, correct_choice_ids, explanation, difficulty, hint) values

-- ===================== Conceitos de Nuvem (+7) =====================
('ccp', 'Conceitos de Nuvem',
 'Antes da nuvem, uma equipe esperava 8 semanas pela compra de servidores para testar uma ideia. Na AWS, o mesmo ambiente sobe em minutos. Qual benefício da nuvem esse contraste ilustra?',
 '[{"id":"a","text":"Agilidade e velocidade de experimentação"},{"id":"b","text":"Durabilidade de 11 noves"},{"id":"c","text":"Modelo de responsabilidade compartilhada"},{"id":"d","text":"Conformidade com PCI DSS"}]',
 '{a}',
 'Provisionar em minutos reduz o custo de experimentar — o benefício de agilidade/velocidade. Os demais itens não têm relação com o tempo de provisionamento.',
 'easy',
 '8 semanas → minutos. O benefício é sobre VELOCIDADE de tentar coisas novas.'),

('ccp', 'Conceitos de Nuvem',
 'Quais fatores uma empresa deve considerar ao escolher a Região AWS para uma nova aplicação? (Escolha DUAS)',
 '[{"id":"a","text":"Proximidade dos usuários (latência)"},{"id":"b","text":"Requisitos legais de residência de dados"},{"id":"c","text":"A cor do console naquela Região"},{"id":"d","text":"Todas as Regiões têm os mesmos preços e serviços"}]',
 '{a,b}',
 'Latência, conformidade legal, preço e disponibilidade de serviços variam por Região — os dois primeiros são os critérios clássicos. Preços e catálogo NÃO são iguais em todas as Regiões.',
 'easy',
 'Onde estão os usuários e onde a LEI manda os dados ficarem.'),

('ccp', 'Conceitos de Nuvem',
 'Qual pilar do Well-Architected Framework se preocupa em minimizar o impacto ambiental das cargas de trabalho?',
 '[{"id":"a","text":"Otimização de custos"},{"id":"b","text":"Sustentabilidade"},{"id":"c","text":"Confiabilidade"},{"id":"d","text":"Segurança"}]',
 '{b}',
 'Sustentabilidade é o sexto pilar, adicionado para tratar de eficiência energética e impacto ambiental. Custo é sobre dinheiro, não carbono.',
 'easy',
 'É o pilar mais novo do framework — pensa no planeta, não no bolso.'),

('ccp', 'Conceitos de Nuvem',
 'Uma empresa decide abandonar seu CRM interno hospedado em servidores próprios e assinar o Salesforce. Qual estratégia de migração é essa?',
 '[{"id":"a","text":"Rehost"},{"id":"b","text":"Replatform"},{"id":"c","text":"Repurchase"},{"id":"d","text":"Retain"}]',
 '{c}',
 'Repurchase ("drop and shop"): trocar a aplicação por um produto SaaS. Não há migração de código — há troca de produto.',
 'medium',
 'Não mudou de lugar — trocou de PRODUTO, comprando uma assinatura pronta.'),

('ccp', 'Conceitos de Nuvem',
 'Uma empresa usa o Microsoft 365 pelo navegador, sem instalar nem gerenciar nada. Qual modelo de serviço isso representa?',
 '[{"id":"a","text":"IaaS"},{"id":"b","text":"PaaS"},{"id":"c","text":"SaaS"},{"id":"d","text":"On-premises"}]',
 '{c}',
 'Software pronto consumido pela internet, sem gerenciar infraestrutura ou plataforma = SaaS.',
 'easy',
 'Você só USA o software — nem código, nem servidor, nem plataforma.'),

('ccp', 'Conceitos de Nuvem',
 'O que é uma Zona de Disponibilidade (AZ)?',
 '[{"id":"a","text":"Um ou mais datacenters isolados, com energia e rede independentes, dentro de uma Região"},{"id":"b","text":"Um ponto de cache do CloudFront"},{"id":"c","text":"Uma conta AWS separada"},{"id":"d","text":"Um datacenter compartilhado entre Regiões"}]',
 '{a}',
 'AZ = agrupamento de datacenters isolados dentro de uma Região, conectados por links de baixa latência. AZs não são compartilhadas entre Regiões; cache de borda é edge location.',
 'easy',
 'É a unidade de isolamento DENTRO de uma Região — falha em uma não derruba a outra.'),

('ccp', 'Conceitos de Nuvem',
 'Qual componente da infraestrutura global da AWS existe em MAIOR quantidade?',
 '[{"id":"a","text":"Regiões"},{"id":"b","text":"Zonas de Disponibilidade"},{"id":"c","text":"Edge locations (pontos de presença)"},{"id":"d","text":"Datacenters de suporte"}]',
 '{c}',
 'Edge locations são centenas — muito mais numerosas que AZs, que por sua vez superam as Regiões. É essa capilaridade que dá baixa latência ao CloudFront.',
 'medium',
 'A hierarquia é uma pirâmide: poucas Regiões, mais AZs, MUITOS pontos de borda.'),

-- ===================== Segurança e Conformidade (+10) =====================
('ccp', 'Segurança e Conformidade',
 'Qual é a diferença entre um grupo IAM e uma role IAM?',
 '[{"id":"a","text":"Grupo organiza usuários para aplicar políticas; role é uma identidade temporária assumível por serviços ou usuários"},{"id":"b","text":"São sinônimos"},{"id":"c","text":"Role organiza usuários; grupo dá credenciais temporárias"},{"id":"d","text":"Grupos são pagos, roles são gratuitas"}]',
 '{a}',
 'Grupo = organização de usuários (política no grupo vale para todos). Role = identidade assumível com credenciais temporárias (EC2, Lambda, cross-account).',
 'medium',
 'Um é uma PASTA de pessoas; o outro é um CRACHÁ temporário que se veste e se devolve.'),

('ccp', 'Segurança e Conformidade',
 'Um administrador quer conceder a um estagiário apenas a permissão de LER objetos de um único bucket S3, nada mais. Qual princípio ele está aplicando?',
 '[{"id":"a","text":"Defesa em profundidade"},{"id":"b","text":"Menor privilégio"},{"id":"c","text":"Responsabilidade compartilhada"},{"id":"d","text":"Separação de contas"}]',
 '{b}',
 'Conceder somente as permissões necessárias para a tarefa = princípio do menor privilégio, a prática nº 1 do IAM.',
 'easy',
 'Só o necessário, nada além — o princípio tem nome de "mínimo".'),

('ccp', 'Segurança e Conformidade',
 'Uma empresa quer verificar continuamente se os recursos seguem regras internas (ex: "todo volume EBS deve ser criptografado") e ver o histórico de configuração de cada recurso. Qual serviço usar?',
 '[{"id":"a","text":"AWS CloudTrail"},{"id":"b","text":"AWS Config"},{"id":"c","text":"Amazon CloudWatch"},{"id":"d","text":"AWS Systems Manager"}]',
 '{b}',
 'Config avalia recursos contra regras de conformidade e mantém o histórico de configuração. CloudTrail registra CHAMADAS, não o estado dos recursos.',
 'medium',
 '"O recurso ESTÁ como deveria estar?" — é sobre estado/configuração, não sobre quem chamou a API.'),

('ccp', 'Segurança e Conformidade',
 'Um cliente pode executar testes de invasão (pentests) nas próprias instâncias EC2?',
 '[{"id":"a","text":"Sim, para serviços permitidos na política da AWS, sem aprovação prévia"},{"id":"b","text":"Não, pentests são proibidos na AWS"},{"id":"c","text":"Sim, mas apenas com autorização por escrito para cada teste"},{"id":"d","text":"Somente com o plano de suporte Enterprise"}]',
 '{a}',
 'A AWS permite pentests nos serviços da lista aprovada (EC2, RDS, CloudFront etc.) sem pedir autorização. Ataques de DDoS simulados e afins continuam exigindo acordo.',
 'hard',
 'A política mudou anos atrás: para a lista de serviços permitidos, não é preciso pedir permissão.'),

('ccp', 'Segurança e Conformidade',
 'No modelo de responsabilidade compartilhada, o que é responsabilidade do CLIENTE ao usar Amazon S3? (Escolha DUAS)',
 '[{"id":"a","text":"Definir políticas de acesso ao bucket"},{"id":"b","text":"Durabilidade física dos discos"},{"id":"c","text":"Escolher criptografar os dados"},{"id":"d","text":"Manutenção dos datacenters"}]',
 '{a,c}',
 'No S3 (serviço gerenciado), o cliente controla ACESSO e proteção DOS DADOS (políticas, criptografia, versionamento). Hardware e instalações são da AWS.',
 'medium',
 'A AWS cuida DO balde; você decide quem abre e se o conteúdo vai trancado.'),

('ccp', 'Segurança e Conformidade',
 'Quais tarefas SÓ podem ser executadas pelo usuário root da conta? (Escolha DUAS)',
 '[{"id":"a","text":"Encerrar (fechar) a conta AWS"},{"id":"b","text":"Criar usuários IAM"},{"id":"c","text":"Alterar o plano de suporte"},{"id":"d","text":"Criar buckets S3"}]',
 '{a,c}',
 'Fechar a conta e mudar o plano de suporte são tarefas exclusivas do root (junto com alterar dados fiscais/de cobrança). Criar usuários e buckets é rotina de administrador IAM.',
 'medium',
 'Pense no que é "dono do contrato": encerrar o contrato e mudar o nível do contrato.'),

('ccp', 'Segurança e Conformidade',
 'Qual serviço emite e renova automaticamente certificados TLS/SSL públicos gratuitos para uso com ELB e CloudFront?',
 '[{"id":"a","text":"AWS KMS"},{"id":"b","text":"AWS Certificate Manager (ACM)"},{"id":"c","text":"AWS Secrets Manager"},{"id":"d","text":"Amazon Cognito"}]',
 '{b}',
 'ACM emite certificados públicos gratuitos com renovação automática, integrados a ELB, CloudFront e API Gateway. KMS gerencia chaves de criptografia, não certificados.',
 'easy',
 'HTTPS de graça com renovação automática — o "gerente de certificados".'),

('ccp', 'Segurança e Conformidade',
 'Uma equipe usa várias contas AWS e quer que os funcionários façam login uma única vez com as credenciais corporativas para acessar todas elas. Qual serviço resolve?',
 '[{"id":"a","text":"IAM Identity Center"},{"id":"b","text":"Amazon Cognito"},{"id":"c","text":"AWS Directory Service isolado"},{"id":"d","text":"Chaves de acesso compartilhadas"}]',
 '{a}',
 'IAM Identity Center (ex-AWS SSO) dá login único federado a múltiplas contas com permission sets. Cognito é para usuários de APLICAÇÕES, não da AWS.',
 'medium',
 'SSO corporativo para contas AWS tem um serviço com "Identity Center" no nome.'),

('ccp', 'Segurança e Conformidade',
 'O que o AWS Shield Standard oferece e quanto custa?',
 '[{"id":"a","text":"Proteção contra ataques DDoS comuns, ativada automaticamente e sem custo"},{"id":"b","text":"Firewall de aplicação web por assinatura"},{"id":"c","text":"Proteção contra vírus nas instâncias"},{"id":"d","text":"Criptografia de dados em repouso, paga por GB"}]',
 '{a}',
 'Shield Standard protege contra DDoS de camada 3/4 automaticamente, sem custo, para todos os clientes. A versão Advanced (paga) adiciona proteções e equipe de resposta.',
 'easy',
 'O "escudo" básico vem de fábrica e de graça para todo mundo.'),

('ccp', 'Segurança e Conformidade',
 'Qual serviço ajuda a coletar evidências e gerenciar auditorias de conformidade de forma contínua nas SUAS cargas de trabalho?',
 '[{"id":"a","text":"AWS Audit Manager"},{"id":"b","text":"AWS Artifact"},{"id":"c","text":"Amazon Inspector"},{"id":"d","text":"AWS Organizations"}]',
 '{a}',
 'Audit Manager coleta evidências das SUAS configurações automaticamente para frameworks de auditoria. Artifact baixa relatórios DA AWS (auditorias que a AWS sofreu) — a pegadinha clássica.',
 'hard',
 'Artifact = evidências DA AWS; o outro serviço coleta evidências SUAS. Qual tem "auditoria" no nome?'),

-- ===================== Tecnologia e Serviços (+13) =====================
('ccp', 'Tecnologia e Serviços',
 'Um desenvolvedor quer publicar uma aplicação web sem administrar infraestrutura, mas mantendo acesso aos recursos criados (instâncias, ASG) se precisar. Qual serviço equilibra automação com controle?',
 '[{"id":"a","text":"AWS Elastic Beanstalk"},{"id":"b","text":"AWS Lambda"},{"id":"c","text":"Amazon Lightsail"},{"id":"d","text":"Amazon WorkSpaces"}]',
 '{a}',
 'Beanstalk provisiona e orquestra tudo (EC2, ASG, ELB) a partir do código, mas os recursos ficam visíveis e acessíveis na conta. Lambda abstrai completamente.',
 'medium',
 'Automatiza o provisionamento SEM esconder os recursos — você ainda pode abrir o capô.'),

('ccp', 'Tecnologia e Serviços',
 'Qual é a durabilidade de objetos projetada do Amazon S3 Standard?',
 '[{"id":"a","text":"99,5%"},{"id":"b","text":"99,99%"},{"id":"c","text":"99,999999999% (11 noves)"},{"id":"d","text":"100% garantida em contrato"}]',
 '{c}',
 'S3 é projetado para 11 noves de durabilidade (não perder objetos). Disponibilidade (conseguir acessar agora) é outra métrica, menor.',
 'easy',
 'O número famoso do S3: onze noves. Durabilidade ≠ disponibilidade.'),

('ccp', 'Tecnologia e Serviços',
 'Como criar uma cópia de segurança de um volume EBS que possa ser restaurada em outra AZ?',
 '[{"id":"a","text":"Criar um snapshot do volume"},{"id":"b","text":"Arrastar o volume para outra AZ no console"},{"id":"c","text":"Ativar Multi-AZ no EBS"},{"id":"d","text":"EBS já replica entre AZs automaticamente"}]',
 '{a}',
 'Snapshots são armazenados no S3 (regional) e podem restaurar volumes em qualquer AZ da Região. EBS em si vive em UMA AZ e não tem "Multi-AZ".',
 'easy',
 'O EBS é preso à AZ; a "foto" dele vive no S3 e pode ser revelada em qualquer AZ.'),

('ccp', 'Tecnologia e Serviços',
 'Qual serviço registra domínios, gerencia DNS e roteia usuários com base em políticas como latência e failover?',
 '[{"id":"a","text":"Amazon CloudFront"},{"id":"b","text":"Amazon Route 53"},{"id":"c","text":"AWS Direct Connect"},{"id":"d","text":"Elastic Load Balancing"}]',
 '{b}',
 'Route 53 é o DNS gerenciado da AWS (o nome vem da porta 53). CloudFront é CDN; ELB balanceia dentro da infraestrutura.',
 'easy',
 'A porta padrão do DNS está no nome do serviço.'),

('ccp', 'Tecnologia e Serviços',
 'Uma empresa precisa de conexão de rede dedicada e privada entre seu datacenter e a AWS, sem passar pela internet. Qual serviço atende?',
 '[{"id":"a","text":"AWS Site-to-Site VPN"},{"id":"b","text":"AWS Direct Connect"},{"id":"c","text":"Amazon CloudFront"},{"id":"d","text":"VPC Peering"}]',
 '{b}',
 'Direct Connect é o link físico dedicado que não trafega pela internet pública. VPN é criptografada mas VIAJA pela internet.',
 'easy',
 '"Dedicada e sem internet" = cabo físico direto, não túnel sobre a internet.'),

('ccp', 'Tecnologia e Serviços',
 'Toda vez que uma foto chega a um bucket S3, uma função deve gerar uma miniatura automaticamente. Qual combinação implementa isso da forma mais simples?',
 '[{"id":"a","text":"Evento do S3 disparando uma função Lambda"},{"id":"b","text":"Instância EC2 verificando o bucket a cada minuto"},{"id":"c","text":"AWS Batch com agendamento diário"},{"id":"d","text":"Amazon Redshift com trigger"}]',
 '{a}',
 'S3 event → Lambda é o padrão orientado a eventos: sem servidores, executa apenas quando algo chega. Polling com EC2 desperdiça recursos.',
 'easy',
 'Reagir a um EVENTO sem servidor ligado esperando — a dupla clássica do serverless.'),

('ccp', 'Tecnologia e Serviços',
 'Qual serviço fornece desktops virtuais Windows/Linux na nuvem para funcionários remotos?',
 '[{"id":"a","text":"Amazon WorkSpaces"},{"id":"b","text":"Amazon Connect"},{"id":"c","text":"AWS Fargate"},{"id":"d","text":"Amazon AppStream nas instâncias"}]',
 '{a}',
 'WorkSpaces entrega desktops virtuais gerenciados (DaaS). Connect é central de atendimento; Fargate roda containers.',
 'medium',
 'Um "espaço de trabalho" completo, com sistema operacional, entregue pela nuvem.'),

('ccp', 'Tecnologia e Serviços',
 'Uma empresa quer montar uma central de atendimento telefônico na nuvem em poucos dias, com URA e roteamento de chamadas. Qual serviço usar?',
 '[{"id":"a","text":"Amazon Connect"},{"id":"b","text":"Amazon Chime"},{"id":"c","text":"Amazon SNS"},{"id":"d","text":"Amazon Pinpoint"}]',
 '{a}',
 'Connect é o contact center como serviço da AWS. Chime é reuniões; Pinpoint é marketing/engajamento; SNS é notificação.',
 'medium',
 'Central de atendimento = "conectar" clientes a atendentes.'),

('ccp', 'Tecnologia e Serviços',
 'Qual banco gerenciado é compatível com MySQL e PostgreSQL, com performance superior e armazenamento que cresce automaticamente?',
 '[{"id":"a","text":"Amazon Aurora"},{"id":"b","text":"Amazon DynamoDB"},{"id":"c","text":"Amazon Redshift"},{"id":"d","text":"Amazon Neptune"}]',
 '{a}',
 'Aurora é a engine relacional da AWS compatível com MySQL/PostgreSQL, com 6 cópias dos dados em 3 AZs e storage auto-expansível.',
 'easy',
 'O relacional "turbinado" da própria AWS, com nome de aurora boreal.'),

('ccp', 'Tecnologia e Serviços',
 'Para coletar e processar fluxos de dados em tempo real (cliques, telemetria, logs) na escala de milhares de eventos por segundo, qual serviço é indicado?',
 '[{"id":"a","text":"Amazon Kinesis"},{"id":"b","text":"AWS Backup"},{"id":"c","text":"Amazon S3 Glacier"},{"id":"d","text":"AWS CloudFormation"}]',
 '{a}',
 'Kinesis é a família de streaming em tempo real. Glacier é arquivamento (o oposto de tempo real).',
 'easy',
 '"Tempo real" + "fluxo contínuo" = o serviço de streaming da AWS.'),

('ccp', 'Tecnologia e Serviços',
 'Qual serviço coordena múltiplas funções Lambda em um fluxo de trabalho visual com etapas, decisões e tratamento de erros?',
 '[{"id":"a","text":"AWS Step Functions"},{"id":"b","text":"Amazon SQS"},{"id":"c","text":"AWS X-Ray"},{"id":"d","text":"Amazon EventBridge"}]',
 '{a}',
 'Step Functions orquestra workflows em máquinas de estado visuais, com retries e ramificações. SQS enfileira; EventBridge roteia eventos; X-Ray rastreia.',
 'medium',
 'Um fluxo com "passos", decisões e retries desenhado visualmente.'),

('ccp', 'Tecnologia e Serviços',
 'Um site quer proteger formulários contra bots e ataques de injeção de SQL. Qual serviço aplica essas regras?',
 '[{"id":"a","text":"AWS WAF"},{"id":"b","text":"AWS Shield Standard"},{"id":"c","text":"Amazon GuardDuty"},{"id":"d","text":"AWS KMS"}]',
 '{a}',
 'WAF filtra requisições web (camada 7): SQL injection, XSS, bots, rate limiting. Shield cuida de DDoS volumétrico; GuardDuty detecta, não bloqueia.',
 'easy',
 'Firewall de APLICAÇÃO web — regras sobre o conteúdo das requisições HTTP.'),

('ccp', 'Tecnologia e Serviços',
 'Qual ferramenta permite executar comandos e scripts em uma frota de instâncias EC2 sem abrir portas SSH, além de gerenciar patches?',
 '[{"id":"a","text":"AWS Systems Manager"},{"id":"b","text":"AWS CloudShell"},{"id":"c","text":"Amazon Inspector"},{"id":"d","text":"AWS Config"}]',
 '{a}',
 'Systems Manager (Session Manager, Run Command, Patch Manager) opera a frota sem SSH exposto. CloudShell é um terminal para VOCÊ usar a CLI, não para gerenciar frotas.',
 'medium',
 'O "gerente de sistemas" da frota: sessões, comandos e patches sem porta 22 aberta.'),

-- ===================== Cobrança, Preços e Suporte (extra para fechar 66) =====================
('ccp', 'Cobrança, Preços e Suporte',
 'Qual recurso permite testar gratuitamente serviços da AWS por 12 meses após criar a conta?',
 '[{"id":"a","text":"AWS Free Tier"},{"id":"b","text":"AWS Credits ilimitados"},{"id":"c","text":"Plano de suporte Basic"},{"id":"d","text":"Savings Plans"}]',
 '{a}',
 'O Free Tier inclui ofertas de 12 meses (EC2, S3, RDS), ofertas sempre gratuitas (Lambda) e trials curtos. O plano Basic é suporte, não uso de serviços.',
 'easy',
 'O "andar grátis" da AWS tem três sabores: 12 meses, sempre grátis e trials.')

on conflict do nothing;
