-- SAA: expansão para o número oficial do exame (+29, distribuição por peso de domínio).

insert into questions (cert_id, domain, prompt, choices, correct_choice_ids, explanation, difficulty, hint) values

-- ===================== Arquiteturas Seguras (+11) =====================
('saa', 'Arquiteturas Seguras',
 'Uma equipe de desenvolvimento pode criar roles IAM, mas a empresa quer garantir que NENHUMA role criada por eles exceda um conjunto máximo de permissões. Qual mecanismo aplica esse teto?',
 '[{"id":"a","text":"Permissions boundary anexada às roles criadas"},{"id":"b","text":"Adicionar os desenvolvedores a um grupo com menos permissões"},{"id":"c","text":"MFA obrigatório"},{"id":"d","text":"Política inline em cada role"}]',
 '{a}',
 'Permissions boundary define o máximo que uma identidade pode ter, independentemente das políticas anexadas — o mecanismo para delegar criação de roles com segurança. Grupo limita OS DESENVOLVEDORES, não as roles que eles criam.',
 'hard',
 'Existe um "contorno de permissões" que age como teto para identidades criadas por terceiros.'),

('saa', 'Arquiteturas Seguras',
 'A conta A precisa que aplicações da conta B leiam sua tabela DynamoDB, sem criar usuários IAM adicionais. Qual é o padrão recomendado?',
 '[{"id":"a","text":"Role na conta A com trust policy para a conta B; aplicações da B assumem a role via STS"},{"id":"b","text":"Copiar a tabela para a conta B diariamente"},{"id":"c","text":"Compartilhar chaves de acesso da conta A"},{"id":"d","text":"Tornar a tabela pública"}]',
 '{a}',
 'Acesso cross-account = role com trust policy + sts:AssumeRole. Sem credenciais permanentes trafegando. DynamoDB não tem "público" e compartilhar chaves é a antipratica clássica.',
 'medium',
 'O padrão cross-account é sempre o mesmo: role de um lado, AssumeRole do outro.'),

('saa', 'Arquiteturas Seguras',
 'Administradores precisam acessar o shell de instâncias EC2 em subnets privadas SEM bastion host, SEM chaves SSH e com sessões auditadas. Qual solução?',
 '[{"id":"a","text":"AWS Systems Manager Session Manager"},{"id":"b","text":"Abrir a porta 22 para 0.0.0.0/0"},{"id":"c","text":"VPN + chaves SSH compartilhadas"},{"id":"d","text":"EC2 Instance Connect via internet"}]',
 '{a}',
 'Session Manager dá shell via agente SSM + IAM, sem portas abertas nem chaves, com log de sessões no CloudTrail/S3. É a resposta moderna para "acesso administrativo seguro".',
 'medium',
 'O acesso sem porta 22 e sem chave passa por um "gerenciador de sessões" do Systems Manager.'),

('saa', 'Arquiteturas Seguras',
 'Um endpoint público de API sofre com clientes abusivos fazendo milhares de requisições por segundo de alguns IPs. Como limitar sem afetar os demais usuários?',
 '[{"id":"a","text":"Regra rate-based no AWS WAF"},{"id":"b","text":"Desligar o endpoint nos horários de pico"},{"id":"c","text":"Aumentar a frota de backend"},{"id":"d","text":"Mover para outra região"}]',
 '{a}',
 'Regras rate-based do WAF bloqueiam automaticamente IPs que excedem o limite de requisições, sem tocar nos usuários legítimos. Escalar o backend só paga a conta do abuso.',
 'easy',
 'O firewall de aplicação tem um tipo de regra "baseada em taxa" feito exatamente para isso.'),

('saa', 'Arquiteturas Seguras',
 'Antes de implantar AMIs em produção, a empresa quer varrê-las automaticamente em busca de CVEs conhecidos. Qual serviço?',
 '[{"id":"a","text":"Amazon Inspector"},{"id":"b","text":"Amazon GuardDuty"},{"id":"c","text":"AWS Shield"},{"id":"d","text":"Amazon Detective"}]',
 '{a}',
 'Inspector varre EC2, ECR e Lambda por vulnerabilidades (CVEs) e exposição de rede. GuardDuty detecta ameaças ATIVAS; Detective investiga incidentes.',
 'easy',
 'Vulnerabilidade conhecida (CVE) = "inspeção"; ameaça em andamento = "guarda".'),

('saa', 'Arquiteturas Seguras',
 'O tráfego entre o ALB e as instâncias EC2 deve ser criptografado de ponta a ponta por exigência de compliance. O que configurar?',
 '[{"id":"a","text":"Listener HTTPS no ALB e certificado também nas instâncias, com target group em HTTPS"},{"id":"b","text":"Apenas HTTPS no ALB; o tráfego interno pode ser HTTP"},{"id":"c","text":"Security groups mais restritos"},{"id":"d","text":"NACL bloqueando a porta 80"}]',
 '{a}',
 'Ponta a ponta = TLS até o destino final: o ALB re-encripta para o backend (target group HTTPS) e as instâncias apresentam certificado. Só HTTPS no front deixa o trecho interno em claro.',
 'medium',
 '"Ponta a ponta" significa que NENHUM trecho viaja em claro — nem o de dentro da VPC.'),

('saa', 'Arquiteturas Seguras',
 'Uma aplicação DR multi-região precisa descriptografar na região secundária os dados criptografados com KMS na primária. Qual recurso viabiliza isso?',
 '[{"id":"a","text":"Multi-Region Keys do KMS"},{"id":"b","text":"Chaves aws/s3 padrão"},{"id":"c","text":"Exportar a chave e importar na outra região"},{"id":"d","text":"CloudHSM público"}]',
 '{a}',
 'Multi-Region Keys são réplicas da mesma chave em outras regiões — mesmo material, IDs relacionados — permitindo decrypt onde os dados forem replicados. Chaves KMS comuns não saem da região.',
 'hard',
 'Chave KMS normal é presa à região; existe uma variante criada exatamente para replicação entre regiões.'),

('saa', 'Arquiteturas Seguras',
 'Um bucket S3 tem Block Public Access ativado na conta e uma bucket policy que permite leitura pública. Qual é o resultado?',
 '[{"id":"a","text":"O acesso público continua bloqueado — Block Public Access prevalece"},{"id":"b","text":"A bucket policy vence e o bucket fica público"},{"id":"c","text":"Erro de configuração impede salvar a policy"},{"id":"d","text":"Só objetos novos ficam públicos"}]',
 '{a}',
 'Block Public Access é um guarda-chuva que IGNORA/bloqueia policies públicas (na conta ou no bucket). É a proteção contra exposição acidental — e por isso a prova adora essa interação.',
 'medium',
 'O recurso foi criado para ser a ÚLTIMA palavra contra exposição acidental. Quem vence?'),

('saa', 'Arquiteturas Seguras',
 'Usuários federados via SAML do Active Directory corporativo precisam de acesso temporário ao console AWS. Qual serviço emite as credenciais temporárias?',
 '[{"id":"a","text":"AWS STS"},{"id":"b","text":"Amazon Cognito User Pools"},{"id":"c","text":"AWS KMS"},{"id":"d","text":"IAM Access Analyzer"}]',
 '{a}',
 'STS (AssumeRoleWithSAML) troca a asserção SAML por credenciais temporárias. Cognito é para usuários de aplicações; Access Analyzer audita permissões.',
 'medium',
 'O "cartório" de credenciais temporárias da AWS tem três letras.'),

('saa', 'Arquiteturas Seguras',
 'A empresa quer descobrir quais recursos (buckets, roles, KMS keys) estão acessíveis de FORA da conta, antes que virem incidente. Qual ferramenta faz essa análise contínua?',
 '[{"id":"a","text":"IAM Access Analyzer"},{"id":"b","text":"AWS Config sozinho"},{"id":"c","text":"Amazon Macie"},{"id":"d","text":"AWS Artifact"}]',
 '{a}',
 'Access Analyzer usa raciocínio automatizado para achar recursos compartilhados com entidades externas (outras contas, público). Macie olha DADOS sensíveis, não permissões.',
 'hard',
 'O nome entrega: analisa ACESSOS e avisa o que está exposto para fora da sua zona de confiança.'),

('saa', 'Arquiteturas Seguras',
 'Uma fintech precisa que o tráfego entre a VPC de produção e o serviço de pagamento de um parceiro (também na AWS) nunca passe pela internet, sem fazer peering das redes. Qual solução?',
 '[{"id":"a","text":"AWS PrivateLink (endpoint service do parceiro)"},{"id":"b","text":"VPC Peering completo"},{"id":"c","text":"NAT Gateway + allowlist de IPs"},{"id":"d","text":"Site-to-Site VPN pela internet"}]',
 '{a}',
 'PrivateLink expõe SÓ o serviço do parceiro como endpoint privado na sua VPC — sem mesclar redes, sem internet, sem CIDR conflitando. Peering abriria a rede inteira.',
 'medium',
 'Você quer UM serviço do parceiro, não a rede inteira dele — e sem internet no caminho.'),

-- ===================== Arquiteturas Resilientes (+8) =====================
('saa', 'Arquiteturas Resilientes',
 'Um RDS PostgreSQL precisa de recuperação a qualquer ponto no tempo dos últimos 14 dias (point-in-time recovery). O que garante isso?',
 '[{"id":"a","text":"Backups automatizados habilitados com retenção de 14 dias"},{"id":"b","text":"Snapshots manuais semanais"},{"id":"c","text":"Read replica na mesma região"},{"id":"d","text":"Multi-AZ"}]',
 '{a}',
 'Backups automatizados (snapshot diário + transaction logs) permitem restaurar para QUALQUER segundo dentro da retenção. Snapshots manuais só restauram para o momento do snapshot; Multi-AZ é failover, não histórico.',
 'medium',
 'PITR precisa dos LOGS contínuos, que só o backup automatizado guarda.'),

('saa', 'Arquiteturas Resilientes',
 'Uma aplicação global exige que, se a região primária cair, o banco relacional esteja disponível em outra região com RPO de ~1 segundo e RTO de ~1 minuto. Qual solução?',
 '[{"id":"a","text":"Aurora Global Database"},{"id":"b","text":"RDS Multi-AZ"},{"id":"c","text":"Snapshots copiados de hora em hora"},{"id":"d","text":"DynamoDB Streams"}]',
 '{a}',
 'Aurora Global Database replica para regiões secundárias com lag típico <1s e promove a secundária em ~1 min. Multi-AZ não atravessa regiões; snapshots horários dão RPO de até 1h.',
 'medium',
 'Existe um modo "global" do Aurora feito exatamente para esse RPO/RTO entre regiões.'),

('saa', 'Arquiteturas Resilientes',
 'Milhares de dispositivos IoT enviam eventos que DEVEM ser processados na ordem exata por dispositivo, sem duplicatas. Qual configuração de fila atende?',
 '[{"id":"a","text":"SQS FIFO com MessageGroupId por dispositivo"},{"id":"b","text":"SQS Standard com long polling"},{"id":"c","text":"SNS com uma inscrição por dispositivo"},{"id":"d","text":"SQS Standard com DLQ"}]',
 '{a}',
 'FIFO garante ordem e deduplicação; MessageGroupId preserva a ordem POR DISPOSITIVO mantendo paralelismo entre dispositivos. Standard não garante nenhum dos dois.',
 'medium',
 'Ordem estrita + sem duplicatas = FIFO. O agrupamento por dispositivo tem um campo próprio.'),

('saa', 'Arquiteturas Resilientes',
 'Um fluxo de aprovação tem 5 etapas com chamadas a Lambdas e uma espera de até 3 dias por aprovação humana. Qual serviço orquestra isso SEM manter computação rodando durante a espera?',
 '[{"id":"a","text":"AWS Step Functions (Standard workflow com task token)"},{"id":"b","text":"Uma Lambda com sleep de 3 dias"},{"id":"c","text":"EC2 com cron"},{"id":"d","text":"SQS com visibility timeout de 3 dias"}]',
 '{a}',
 'Step Functions Standard mantém o estado por até 1 ano sem computação ativa; o task token pausa até o callback humano. Lambda morre em 15 min; visibility timeout máximo do SQS é 12h.',
 'hard',
 'O orquestrador guarda o ESTADO do fluxo por meses sem nenhum servidor ligado esperando.'),

('saa', 'Arquiteturas Resilientes',
 'Durante o scale-in do Auto Scaling, conexões ativas são derrubadas abruptamente. Como encerrar instâncias sem cortar requisições em andamento?',
 '[{"id":"a","text":"Habilitar connection draining (deregistration delay) no target group"},{"id":"b","text":"Desativar o scale-in"},{"id":"c","text":"Usar instâncias maiores"},{"id":"d","text":"Reduzir o health check interval"}]',
 '{a}',
 'Deregistration delay mantém a instância recebendo apenas as conexões JÁ abertas até concluí-las (ou até o timeout) antes do encerramento. Desativar scale-in joga dinheiro fora.',
 'medium',
 'O target group tem um "tempo de despedida" para a instância terminar o que começou.'),

('saa', 'Arquiteturas Resilientes',
 'Uma aplicação usa EFS como armazenamento compartilhado. O arquiteto pergunta: o que é necessário para o EFS sobreviver à falha de uma AZ?',
 '[{"id":"a","text":"Nada — EFS Standard já replica os dados entre múltiplas AZs"},{"id":"b","text":"Configurar replicação manual entre volumes"},{"id":"c","text":"Snapshots por hora"},{"id":"d","text":"EFS não sobrevive a falha de AZ"}]',
 '{a}',
 'EFS Standard é regional e redundante entre AZs por design (mount targets em cada AZ). A classe One Zone é a exceção que vive em uma AZ só.',
 'easy',
 'O EFS "normal" é REGIONAL por natureza — quem mora numa AZ só é a variante One Zone.'),

('saa', 'Arquiteturas Resilientes',
 'Para lançar uma nova versão com risco controlado, a empresa quer enviar 5% do tráfego para a versão nova e aumentar gradualmente, com rollback via DNS. Qual política do Route 53?',
 '[{"id":"a","text":"Weighted routing"},{"id":"b","text":"Geolocation routing"},{"id":"c","text":"Simple routing"},{"id":"d","text":"Multivalue answer"}]',
 '{a}',
 'Weighted distribui por pesos (95/5 → 80/20 → ...), o padrão canary via DNS. Rollback = voltar o peso a zero.',
 'easy',
 'Distribuição percentual do tráfego = política de PESOS.'),

('saa', 'Arquiteturas Resilientes',
 'Um sistema de arquivamento precisa apenas de backups diários com restauração aceitável em até 24h, ao MENOR custo de DR. Qual estratégia?',
 '[{"id":"a","text":"Backup & Restore (backups para S3/Glacier em outra região)"},{"id":"b","text":"Warm standby"},{"id":"c","text":"Multi-site ativo-ativo"},{"id":"d","text":"Pilot light"}]',
 '{a}',
 'RTO de 24h não justifica infraestrutura de prontidão: backup & restore é a estratégia mais barata que ATENDE o requisito — a regra de ouro do domínio de DR.',
 'easy',
 'Escolha sempre a estratégia MAIS BARATA que ainda cumpre o RTO/RPO dado.'),

-- ===================== Arquiteturas de Alta Performance (+6) =====================
('saa', 'Arquiteturas de Alta Performance',
 'Uma tabela DynamoDB é consultada por user_id (partition key), mas agora o app precisa buscar pedidos por status e data. Como habilitar o novo padrão de consulta eficientemente?',
 '[{"id":"a","text":"Criar um Global Secondary Index com status/data como chaves"},{"id":"b","text":"Fazer Scan com filtro"},{"id":"c","text":"Migrar para RDS"},{"id":"d","text":"Duplicar a tabela"}]',
 '{a}',
 'GSI cria uma "visão" da tabela com outras chaves, consultável com Query eficiente. Scan lê a tabela INTEIRA — o anti-padrão de performance mais citado na prova.',
 'medium',
 'Consultar por OUTRO atributo sem varrer tudo = índice secundário global.'),

('saa', 'Arquiteturas de Alta Performance',
 'Centenas de Lambdas simultâneas abrem conexões diretas em um RDS PostgreSQL, esgotando o max_connections. Qual solução gerenciada resolve?',
 '[{"id":"a","text":"Amazon RDS Proxy"},{"id":"b","text":"Aumentar max_connections indefinidamente"},{"id":"c","text":"Instância RDS maior a cada pico"},{"id":"d","text":"Uma fila SQS na frente do banco"}]',
 '{a}',
 'RDS Proxy multiplexa milhares de conexões efêmeras da Lambda em um pool estável para o banco. Aumentar limites/instância só empurra o problema.',
 'medium',
 'O problema é POOL de conexões — existe um "porteiro" gerenciado entre Lambda e RDS.'),

('saa', 'Arquiteturas de Alta Performance',
 'Uma simulação científica de HPC exige latência de microssegundos entre dezenas de instâncias que trocam dados intensamente. Qual configuração de posicionamento usar?',
 '[{"id":"a","text":"Cluster placement group (mesma AZ, hardware próximo) com Enhanced Networking"},{"id":"b","text":"Spread placement group"},{"id":"c","text":"Instâncias em 3 AZs"},{"id":"d","text":"Partition placement group em 2 regiões"}]',
 '{a}',
 'Cluster placement group aproxima fisicamente as instâncias para latência mínima e alta banda por fluxo — o trade-off é concentrar o risco. HPC aceita esse trade-off.',
 'medium',
 'Para conversa intensa entre nós, junte-os no mesmo rack — o oposto de espalhar.'),

('saa', 'Arquiteturas de Alta Performance',
 'Um processamento intermediário grava terabytes de arquivos temporários que podem ser perdidos sem prejuízo, mas exigem IOPS altíssimos. Qual armazenamento tem melhor custo/performance?',
 '[{"id":"a","text":"Instance store (NVMe local) de instâncias otimizadas para storage"},{"id":"b","text":"EBS io2 com IOPS provisionadas máximas"},{"id":"c","text":"EFS com throughput provisionado"},{"id":"d","text":"S3 Standard"}]',
 '{a}',
 'Instance store é NVMe físico no host: IOPS massivos sem custo adicional de volume — perfeito para dados TEMPORÁRIOS (efêmero por natureza). io2 topo de linha custa caro para dados descartáveis.',
 'hard',
 'Dados descartáveis + IOPS extremos = o disco FÍSICO da própria máquina, que não cobra por IOPS.'),

('saa', 'Arquiteturas de Alta Performance',
 'Um endpoint REST no API Gateway serve dados que mudam a cada 10 minutos, mas recebe milhares de chamadas idênticas por minuto. Como reduzir a carga no backend imediatamente?',
 '[{"id":"a","text":"Habilitar o cache do API Gateway com TTL adequado"},{"id":"b","text":"Aumentar a concorrência da Lambda"},{"id":"c","text":"Migrar para WebSocket"},{"id":"d","text":"Publicar em duas regiões"}]',
 '{a}',
 'O cache nativo do API Gateway (REST API) responde as chamadas repetidas sem invocar o backend, com TTL configurável. Mais concorrência só processa o desperdício mais rápido.',
 'medium',
 'Respostas idênticas por 10 minutos pedem cache NA porta de entrada.'),

('saa', 'Arquiteturas de Alta Performance',
 'Logs de aplicação precisam de busca full-text quase em tempo real com dashboards para o time de operações. Qual pilha gerenciada?',
 '[{"id":"a","text":"Amazon OpenSearch Service (+ ingestão via Firehose)"},{"id":"b","text":"S3 + Athena"},{"id":"c","text":"RDS MySQL com índice FULLTEXT"},{"id":"d","text":"DynamoDB com GSI"}]',
 '{a}',
 'Busca full-text + dashboards em tempo quase real = OpenSearch (com Firehose entregando). Athena é ótimo para consultas ad-hoc baratas, mas não para busca interativa em near real-time.',
 'medium',
 '"Full-text" + "tempo real" + "dashboards de logs" descrevem o serviço de BUSCA da AWS.'),

-- ===================== Custo Otimizado (+4) =====================
('saa', 'Arquiteturas com Custo Otimizado',
 'Com versionamento habilitado, um bucket S3 acumulou milhões de versões antigas que ninguém acessa, dobrando o custo. Qual solução automática?',
 '[{"id":"a","text":"Lifecycle rule para versões não-correntes: transição para Glacier e expiração"},{"id":"b","text":"Desativar o versionamento (as versões antigas somem)"},{"id":"c","text":"Copiar tudo para outro bucket"},{"id":"d","text":"MFA Delete"}]',
 '{a}',
 'Lifecycle tem ações específicas para versões NÃO-correntes (transicionar/expirar). Suspender versionamento não remove versões existentes — pegadinha clássica.',
 'medium',
 'O lifecycle diferencia a versão ATUAL das antigas — e pode arquivar/apagar só as antigas.'),

('saa', 'Arquiteturas com Custo Otimizado',
 'A análise mostra dezenas de instâncias EC2 com CPU média de 4% há meses. Qual serviço gera recomendações de redimensionamento baseadas em métricas reais?',
 '[{"id":"a","text":"AWS Compute Optimizer"},{"id":"b","text":"AWS Artifact"},{"id":"c","text":"Amazon Inspector"},{"id":"d","text":"AWS Shield"}]',
 '{a}',
 'Compute Optimizer usa ML sobre métricas do CloudWatch para recomendar tipos/tamanhos ideais (EC2, EBS, Lambda). Rightsizing é a alavanca de custo nº 1.',
 'easy',
 'O serviço que "otimiza computação" analisando o uso real e sugerindo o tamanho certo.'),

('saa', 'Arquiteturas com Custo Otimizado',
 'Um ASG precisa de capacidade mínima garantida de 4 instâncias e escala até 20 em picos tolerantes a interrupção. Qual composição minimiza custo com segurança?',
 '[{"id":"a","text":"Mixed instances policy: base de 4 On-Demand/Savings Plans + excedente em Spot"},{"id":"b","text":"20 instâncias reservadas"},{"id":"c","text":"Tudo em Spot"},{"id":"d","text":"Tudo On-Demand"}]',
 '{a}',
 'A base garantida fica em capacidade estável (On-Demand coberta por Savings Plans); o excedente elástico vai em Spot com grande desconto. Tudo Spot arrisca a base; reservar 20 paga ociosidade.',
 'medium',
 'Divida a frota: o "chão" garantido num modelo estável, o "pico" descartável no modelo com desconto máximo.'),

('saa', 'Arquiteturas com Custo Otimizado',
 'Ambientes de desenvolvimento precisam de bancos RDS grandes, mas só em horário comercial. Além de parar as instâncias à noite, qual alternativa serverless elimina o custo ocioso?',
 '[{"id":"a","text":"Aurora Serverless v2, escalando a quase zero fora do expediente"},{"id":"b","text":"RDS Multi-AZ com réplicas"},{"id":"c","text":"DynamoDB provisionado no máximo"},{"id":"d","text":"Instância reservada de 3 anos para dev"}]',
 '{a}',
 'Aurora Serverless v2 escala capacidade automaticamente conforme o uso (inclusive quase zero), pagando por ACU consumida — ideal para cargas intermitentes como dev/test.',
 'medium',
 'Banco que "dorme" quando ninguém usa e cobra pela capacidade consumida.')

on conflict do nothing;
