-- More flashcards per certification, covering every exam domain.

insert into public.flashcards (cert_id, domain, front, back) values
  ('ccp', 'Conceitos de Nuvem', 'CAPEX × OPEX', 'CAPEX: investimento antecipado em ativos (comprar servidores). OPEX: despesa variável conforme o uso (pagar a AWS por hora/GB). A nuvem troca CAPEX por OPEX.'),
  ('ccp', 'Conceitos de Nuvem', 'Os 6 pilares do Well-Architected', 'Excelência operacional, Segurança, Confiabilidade, Eficiência de performance, Otimização de custos e Sustentabilidade.'),
  ('ccp', 'Conceitos de Nuvem', 'As 6 perspectivas do AWS CAF', 'Negócios, Pessoas e Governança (foco no negócio) + Plataforma, Segurança e Operações (foco técnico).'),
  ('ccp', 'Conceitos de Nuvem', 'Rehost × Replatform × Refactor', 'Rehost: mover sem mudar (lift-and-shift). Replatform: pequenos ajustes, como trocar o banco por RDS. Refactor: reescrever para cloud-native (ex: serverless).'),
  ('ccp', 'Conceitos de Nuvem', 'Local Zone × Wavelength × Outposts', 'Local Zone: AWS perto de uma metrópole. Wavelength: AWS dentro da rede 5G da operadora. Outposts: hardware AWS no SEU datacenter.'),
  ('ccp', 'Conceitos de Nuvem', 'Edge location serve para…', 'Pontos de presença usados pelo CloudFront, Route 53 e Global Accelerator para entregar conteúdo e DNS perto do usuário. Existem em maior número que Regiões e AZs.'),
  ('ccp', 'Conceitos de Nuvem', 'Nuvem × híbrido × on-premises', 'Nuvem: tudo na AWS. Híbrido: parte no datacenter, parte na nuvem, conectados (VPN/Direct Connect). On-premises (nuvem privada): tudo em infraestrutura própria.'),
  ('ccp', 'Conceitos de Nuvem', 'IaaS × PaaS × SaaS', 'IaaS: você gerencia SO e app (EC2). PaaS: você só entrega o código (Elastic Beanstalk). SaaS: software pronto, só usa (Microsoft 365).'),
  ('ccp', 'Conceitos de Nuvem', 'Economia de escala', 'A AWS agrega o uso de milhões de clientes, compra em volume e repassa custos menores. Por isso o preço por unidade cai com o tempo.'),
  ('ccp', 'Conceitos de Nuvem', 'Alta disponibilidade × tolerância a falhas', 'Alta disponibilidade: mínimo de indisponibilidade, com recuperação rápida. Tolerância a falhas: continua funcionando sem interrupção mesmo com componentes falhando.'),
  ('ccp', 'Conceitos de Nuvem', 'Princípios de design para a nuvem', 'Projetar para falhas, desacoplar componentes, escalar horizontalmente, automatizar com IaC, usar serviços gerenciados e pagar só pelo necessário.'),
  ('ccp', 'Conceitos de Nuvem', 'Ferramentas de migração', 'MGN: rehost de servidores. DMS: migra bancos com mínima parada. SCT: converte esquemas entre motores. DataSync: transfere arquivos online. Snowball: transfere offline.'),
  ('ccp', 'Conceitos de Nuvem', '4 fatores para escolher uma Região', 'Conformidade e residência de dados, latência para os usuários, serviços disponíveis e preço (varia por Região).'),
  ('ccp', 'Segurança e Conformidade', 'Security group × NACL', 'SG: nível da instância, stateful, só regras de allow. NACL: nível da sub-rede, stateless, allow e deny, regras avaliadas em ordem numérica.'),
  ('ccp', 'Segurança e Conformidade', 'Controles herdados × compartilhados × do cliente', 'Herdados: vêm prontos da AWS (físicos e ambientais). Compartilhados: cada um na sua camada (patches, configuração, treinamento). Do cliente: dados, IAM, criptografia escolhida.'),
  ('ccp', 'Segurança e Conformidade', 'KMS × CloudHSM', 'KMS: chaves gerenciadas em HSMs compartilhados, integrado a quase todos os serviços. CloudHSM: HSM dedicado de locatário único, você controla as chaves e os usuários.'),
  ('ccp', 'Segurança e Conformidade', 'Shield Standard × Advanced', 'Standard: grátis e automático, protege contra DDoS comuns (camadas 3 e 4). Advanced: pago, com Shield Response Team 24/7, detecção avançada e proteção de custos.'),
  ('ccp', 'Segurança e Conformidade', 'AWS WAF bloqueia…', 'Ataques na camada 7 (HTTP): injeção de SQL, XSS, bots, IPs e países específicos e excesso de requisições (rate-based). Funciona com CloudFront, ALB e API Gateway.'),
  ('ccp', 'Segurança e Conformidade', 'Security Hub × Detective', 'Security Hub: painel central de findings e verificação contra padrões (CIS, FSBP). Detective: investiga a causa raiz de um finding com grafos de atividade.'),
  ('ccp', 'Segurança e Conformidade', 'IAM Identity Center × Cognito', 'Identity Center: login único dos FUNCIONÁRIOS em várias contas AWS e apps. Cognito: cadastro e login dos CLIENTES de uma aplicação web ou mobile.'),
  ('ccp', 'Segurança e Conformidade', 'SCP em uma frase', 'Teto de permissões para contas de uma OU no Organizations. Não concede nada; limita até o root das contas-membro. Não afeta a conta de gerenciamento.'),
  ('ccp', 'Segurança e Conformidade', 'IAM Access Analyzer encontra…', 'Recursos (buckets, roles, chaves KMS, filas) acessíveis por quem está FORA da conta ou da organização, além de permissões não utilizadas.'),
  ('ccp', 'Segurança e Conformidade', 'Relatório de credenciais do IAM', 'CSV com todos os usuários IAM e o estado das credenciais: senha, idade das chaves de acesso e se o MFA está ativo. Útil em auditorias.'),
  ('ccp', 'Segurança e Conformidade', 'Firewall Manager × Control Tower', 'Firewall Manager: aplica regras de WAF, Shield e security groups em todas as contas. Control Tower: cria a landing zone multi-conta com controles (guardrails).'),
  ('ccp', 'Segurança e Conformidade', 'Criptografia em repouso × em trânsito', 'Em repouso: dados armazenados (KMS, SSE-S3, EBS criptografado). Em trânsito: dados trafegando (TLS/HTTPS, certificados do ACM, VPN).'),
  ('ccp', 'Segurança e Conformidade', 'Abuso de recursos AWS: quem avisar?', 'A equipe de Trust & Safety da AWS, pelo formulário de denúncia de abuso (spam, ataques, conteúdo ilegal partindo de recursos AWS).'),
  ('ccp', 'Segurança e Conformidade', 'MFA aceito pela AWS', 'Aplicativo autenticador (TOTP), passkeys e chaves de segurança FIDO2, e tokens físicos TOTP. SMS não é aceito para usuários IAM.'),
  ('ccp', 'Segurança e Conformidade', 'Em serviços gerenciados, o que sobra para o cliente?', 'Sempre: dados, controle de acesso (IAM) e configuração. Em Lambda, também o código. A AWS cuida do SO, do runtime e da infraestrutura.'),
  ('ccp', 'Tecnologia e Serviços', 'Famílias de instâncias EC2', 'T/M: uso geral. C: computação. R/X: memória. I/D: armazenamento local. P/G/Trn/Inf: computação acelerada (GPU e chips de ML).'),
  ('ccp', 'Tecnologia e Serviços', 'ALB × NLB × GWLB', 'ALB: camada 7, rotas por caminho e host. NLB: camada 4 (TCP/UDP), ultrabaixa latência e IP estático. GWLB: insere appliances de terceiros (firewalls).'),
  ('ccp', 'Tecnologia e Serviços', 'ECS × EKS × Fargate', 'ECS: orquestrador de contêineres da AWS. EKS: Kubernetes gerenciado. Fargate: computação serverless para rodar tarefas do ECS ou EKS sem servidores.'),
  ('ccp', 'Tecnologia e Serviços', 'Lightsail em uma linha', 'Servidores virtuais simples com preço mensal fixo, para sites pequenos, blogs e testes.'),
  ('ccp', 'Tecnologia e Serviços', 'Instance store × EBS', 'Instance store: disco local efêmero, rapidíssimo, perde os dados ao parar a instância. EBS: disco de rede persistente na mesma AZ, com snapshots.'),
  ('ccp', 'Tecnologia e Serviços', 'FSx for Windows × FSx for Lustre', 'Windows: compartilhamento SMB integrado ao Active Directory. Lustre: sistema de arquivos paralelo para HPC e ML, integrado ao S3.'),
  ('ccp', 'Tecnologia e Serviços', 'Storage Gateway', 'Ponte híbrida: o datacenter acessa arquivos, volumes ou fitas localmente, com os dados armazenados no S3 e cache local.'),
  ('ccp', 'Tecnologia e Serviços', 'AWS Backup', 'Backups centralizados e automatizados de EC2, EBS, RDS, DynamoDB, EFS e outros, com retenção, cópia entre Regiões e contas e Vault Lock.'),
  ('ccp', 'Tecnologia e Serviços', 'RDS × Aurora × DynamoDB', 'RDS: relacional gerenciado (MySQL, PostgreSQL, Oracle, SQL Server...). Aurora: relacional da AWS, compatível com MySQL/PostgreSQL e mais rápido. DynamoDB: NoSQL chave-valor serverless.'),
  ('ccp', 'Tecnologia e Serviços', 'Redshift × Athena', 'Redshift: data warehouse para análises pesadas e recorrentes. Athena: SQL serverless direto no S3, paga por dado lido, ideal para consultas ad hoc.'),
  ('ccp', 'Tecnologia e Serviços', 'Neptune × DocumentDB × ElastiCache', 'Neptune: banco de grafos (relações). DocumentDB: documentos JSON compatível com MongoDB. ElastiCache: cache em memória (Valkey, Redis OSS, Memcached).'),
  ('ccp', 'Tecnologia e Serviços', 'Sub-rede pública × privada', 'Pública: tabela de rotas com saída para um internet gateway. Privada: sem essa rota; sai para a internet só via NAT gateway.'),
  ('ccp', 'Tecnologia e Serviços', 'Site-to-Site VPN × Direct Connect', 'VPN: túnel IPsec criptografado pela internet, configurado em minutos. Direct Connect: circuito físico dedicado e privado, banda consistente, leva semanas.'),
  ('ccp', 'Tecnologia e Serviços', 'Transit Gateway', 'Hub regional que conecta muitas VPCs e redes locais em estrela, em vez de dezenas de peerings ponto a ponto.'),
  ('ccp', 'Tecnologia e Serviços', 'Serviços de IA prontos', 'Rekognition: imagem/vídeo. Polly: texto→voz. Transcribe: voz→texto. Translate: tradução. Comprehend: sentimento e entidades. Textract: dados de documentos. Lex: chatbots.'),
  ('ccp', 'Tecnologia e Serviços', 'SageMaker AI × Bedrock', 'SageMaker AI: construir, treinar e implantar modelos de ML próprios. Bedrock: usar modelos de fundação prontos via API para IA generativa.'),
  ('ccp', 'Tecnologia e Serviços', 'CodePipeline × CodeBuild × CodeDeploy', 'CodePipeline: orquestra o CI/CD. CodeBuild: compila e testa. CodeDeploy: implanta em EC2, Lambda, ECS ou servidores locais.'),
  ('ccp', 'Tecnologia e Serviços', 'CloudFormation × Elastic Beanstalk', 'CloudFormation: infraestrutura como código (templates). Beanstalk: você envia o código e ele provisiona e gerencia o ambiente.'),
  ('ccp', 'Tecnologia e Serviços', 'Glue × EMR', 'Glue: ETL serverless e Data Catalog. EMR: clusters gerenciados de Spark, Hadoop e outros frameworks de big data.'),
  ('ccp', 'Tecnologia e Serviços', 'Formas de acessar a AWS', 'Console (navegador), CLI e SDKs (programático), CloudShell (terminal no console) e infraestrutura como código (CloudFormation, CDK).'),
  ('ccp', 'Cobrança, Preços e Suporte', 'On-Demand × Savings Plans × RI × Spot × Dedicated', 'On-Demand: sem compromisso. Savings Plans/RI: até ~72% com 1 ou 3 anos. Spot: até 90%, pode ser interrompido. Dedicated Hosts: servidor físico seu, para licenças por núcleo.'),
  ('ccp', 'Cobrança, Preços e Suporte', 'Compute Optimizer × Trusted Advisor', 'Compute Optimizer: recomenda o tamanho certo de EC2, EBS, Lambda etc. pelo uso real. Trusted Advisor: verificações de custo, segurança, performance, resiliência e limites.'),
  ('ccp', 'Cobrança, Preços e Suporte', 'Cost Anomaly Detection', 'Usa ML para aprender o padrão de gastos e alerta sobre picos fora do normal, sem você definir limites manuais.'),
  ('ccp', 'Cobrança, Preços e Suporte', 'Free Tier hoje', 'Contas criadas a partir de 15/07/2025 recebem até US$ 200 em créditos e plano gratuito de até 6 meses. Ofertas sempre grátis continuam (ex: 1 milhão de requisições Lambda/mês).'),
  ('ccp', 'Cobrança, Preços e Suporte', 'Transferência de dados: grátis × cobrada', 'Grátis: entrada na AWS e, em geral, tráfego na mesma AZ. Cobrada: saída para a internet, entre Regiões e entre AZs.'),
  ('ccp', 'Cobrança, Preços e Suporte', 're:Post × Partner Network × Professional Services', 're:Post: comunidade de perguntas e respostas. Partner Network: consultorias e software de parceiros validados. Professional Services: especialistas da própria AWS.'),
  ('ccp', 'Cobrança, Preços e Suporte', 'Service Quotas', 'Mostra os limites de cada serviço por Região e permite pedir aumento.'),
  ('ccp', 'Cobrança, Preços e Suporte', 'Tags de alocação de custo', 'Rótulos (ex: Projeto, Equipe) ativados no Billing para separar custos no Cost Explorer e no CUR.'),
  ('ccp', 'Cobrança, Preços e Suporte', 'Lambda cobra por…', 'Número de requisições + duração em GB-segundo (memória × tempo). Sem execução, sem cobrança de computação.'),
  ('saa', 'Arquiteturas Seguras', 'Presigned URL', 'Acesso temporário a UM objeto privado do S3, com as permissões de quem gerou a URL e prazo de expiração. Serve para download e upload.'),
  ('saa', 'Arquiteturas Seguras', 'Object Lock: governança × compliance', 'Governança: usuários com permissão especial podem remover a trava. Compliance: ninguém, nem o root, apaga ou altera antes do fim da retenção.'),
  ('saa', 'Arquiteturas Seguras', 'Forçar HTTPS no S3', 'Bucket policy com Deny quando aws:SecureTransport = false.'),
  ('saa', 'Arquiteturas Seguras', 'Criptografia de envelope', 'O KMS protege só a chave de dados; a chave de dados criptografa o conteúdo localmente. Evita mandar grandes volumes ao KMS.'),
  ('saa', 'Arquiteturas Seguras', 'SG referenciando outro SG', 'Use o security group do ALB como origem no SG da aplicação: libera qualquer IP do ALB, mesmo que os IPs mudem.'),
  ('saa', 'Arquiteturas Seguras', 'NACL e portas efêmeras', 'NACL é stateless: libere também a SAÍDA para as portas efêmeras (1024-65535) para as respostas chegarem ao cliente.'),
  ('saa', 'Arquiteturas Seguras', 'CloudFront: OAC × signed URL × signed cookies', 'OAC: só o CloudFront lê o bucket. Signed URL: acesso a UM arquivo. Signed cookies: acesso a VÁRIOS arquivos sem mudar as URLs.'),
  ('saa', 'Arquiteturas Seguras', 'Certificado ACM para CloudFront', 'Tem que estar em us-east-1, porque o CloudFront é global. Para ALB, o certificado fica na Região do ALB.'),
  ('saa', 'Arquiteturas Seguras', 'Cognito user pool × identity pool', 'User pool: cadastro e login, emite tokens JWT. Identity pool: troca a identidade por credenciais AWS temporárias (acesso direto a S3, DynamoDB).'),
  ('saa', 'Arquiteturas Seguras', 'ABAC', 'Permissões por tags: aws:PrincipalTag/Projeto = aws:ResourceTag/Projeto. Uma política serve para todos os projetos, inclusive os futuros.'),
  ('saa', 'Arquiteturas Seguras', 'Remediação automática', 'GuardDuty → EventBridge → Lambda (ex: isolar instância). AWS Config regra → SSM Automation (ex: fechar porta 22).'),
  ('saa', 'Arquiteturas Seguras', 'Criptografar um RDS existente', 'Não dá para ligar na instância. Snapshot → copiar com criptografia → restaurar nova instância.'),
  ('saa', 'Arquiteturas Seguras', 'Network Firewall × WAF × SG', 'Network Firewall: inspeção stateful e filtro por domínio na VPC. WAF: camada 7 em ALB, CloudFront, API Gateway. SG: portas e IPs na instância.'),
  ('saa', 'Arquiteturas Seguras', 'Gateway Load Balancer', 'Insere appliances de terceiros (firewall, IDS/IPS) de forma transparente no caminho do tráfego, com GENEVE, escala e health checks.'),
  ('saa', 'Arquiteturas Seguras', 'Organization trail', 'Um único trail do CloudTrail para TODAS as contas da organização, inclusive as novas. Contas-membro não conseguem desligar.'),
  ('saa', 'Arquiteturas Seguras', 'Object Ownership: bucket owner enforced', 'Desativa ACLs: o dono do bucket passa a ser dono de todos os objetos, mesmo os enviados por outras contas.'),
  ('saa', 'Arquiteturas Seguras', 'dynamodb:LeadingKeys', 'Condição IAM que limita o acesso a itens cuja partition key é o ID do usuário (ex: ID do Cognito). Controle por item.'),
  ('saa', 'Arquiteturas Seguras', 'API Gateway privado', 'Endpoint de API acessível só por VPC endpoint de interface (execute-api) + resource policy limitando VPCs ou endpoints.'),
  ('saa', 'Arquiteturas Seguras', 'Criptografar o Direct Connect', 'VPN IPsec sobre o DX, ou MACsec (camada 2) em conexões dedicadas compatíveis. O DX sozinho é privado, mas não criptografado.'),
  ('saa', 'Arquiteturas Seguras', 'IAM Roles Anywhere', 'Servidores fora da AWS obtêm credenciais temporárias de uma role usando certificados X.509 da sua CA. Sem chaves de longa duração.'),
  ('saa', 'Arquiteturas Seguras', 'Administrador delegado', 'Uma conta de segurança gerencia GuardDuty, Security Hub, Inspector etc. para toda a organização, deixando a conta de gerenciamento intocada.'),
  ('saa', 'Arquiteturas Seguras', 'KMS entre contas', 'A key policy da chave gerenciada pelo cliente libera a outra conta E a outra conta dá permissão IAM. Chaves gerenciadas pela AWS não são compartilháveis.'),
  ('saa', 'Arquiteturas Resilientes', 'ASG: health check do ELB', 'Por padrão o ASG só olha o status do EC2. Ative o health check do ELB para substituir instâncias com a aplicação travada.'),
  ('saa', 'Arquiteturas Resilientes', 'Aurora: failover e endpoints', 'Até 15 réplicas no mesmo volume; na falha, uma réplica é promovida (normalmente < 1 min). Cluster endpoint = escrita; reader endpoint = leituras balanceadas.'),
  ('saa', 'Arquiteturas Resilientes', 'DynamoDB global tables × PITR', 'Global tables: multi-Região e multi-ativo. PITR: restaura a tabela em qualquer segundo da janela de retenção (até 35 dias), criando uma tabela nova.'),
  ('saa', 'Arquiteturas Resilientes', 'S3 CRR: requisitos e RTC', 'Versionamento nos dois buckets + role IAM. Só replica objetos novos (para antigos: Batch Replication). RTC: 99,99% em até 15 min, com métricas.'),
  ('saa', 'Arquiteturas Resilientes', 'Pilot light × warm standby', 'Pilot light: só os dados replicados; servidores criados no desastre (horas). Warm standby: cópia reduzida de tudo rodando (minutos).'),
  ('saa', 'Arquiteturas Resilientes', 'Kinesis Data Streams × SQS', 'Kinesis: vários consumidores, ordem por partition key e releitura dentro da retenção. SQS: cada mensagem consumida e apagada; sem replay.'),
  ('saa', 'Arquiteturas Resilientes', 'Lambda assíncrona: destinos', 'Após as tentativas, o evento com o erro vai para um destino on-failure (SQS, SNS, EventBridge, Lambda). Também há destino on-success.'),
  ('saa', 'Arquiteturas Resilientes', 'Step Functions: Retry × Catch', 'Retry: novas tentativas com intervalo e backoff. Catch: desvia o erro para um estado de tratamento. Sem código de retentativa nas funções.'),
  ('saa', 'Arquiteturas Resilientes', 'Recuperação automática de EC2', 'Na falha de hardware, a instância migra de host mantendo ID, IP privado, Elastic IP e metadados. Para servidores únicos que não escalam.'),
  ('saa', 'Arquiteturas Resilientes', 'Backup Vault Lock', 'WORM para pontos de recuperação do AWS Backup: em modo compliance, ninguém apaga antes do prazo. Combine com cópia entre Regiões.'),
  ('saa', 'Arquiteturas Resilientes', 'SQS Standard e duplicatas', 'Entrega pelo menos uma vez: torne o consumidor idempotente (ex: gravar o ID com escrita condicional no DynamoDB antes de processar).'),
  ('saa', 'Arquiteturas Resilientes', 'Backoff exponencial com jitter', 'Aumente o intervalo a cada tentativa e adicione aleatoriedade para os clientes não tentarem todos ao mesmo tempo.'),
  ('saa', 'Arquiteturas Resilientes', 'NAT gateway é zonal', 'Um NAT gateway por AZ, com a rota de cada AZ apontando para o NAT local. Um só NAT vira ponto único de falha.'),
  ('saa', 'Arquiteturas Resilientes', 'Contingência do Direct Connect', 'Mais barata: VPN Site-to-Site como backup. Máxima resiliência: duas conexões DX em locais diferentes.'),
  ('saa', 'Arquiteturas Resilientes', 'Reserved × provisioned concurrency', 'Reserved: garante e LIMITA execuções simultâneas (protege o banco). Provisioned: instâncias pré-aquecidas contra cold start, sem impor limite.'),
  ('saa', 'Arquiteturas Resilientes', 'Evaluate target health', 'Em registros alias do Route 53, herda a saúde do destino (ex: ALB sem alvos saudáveis) para acionar failover sem health check separado.'),
  ('saa', 'Arquiteturas Resilientes', 'Instance refresh', 'Troca gradual das instâncias do ASG (nova AMI ou launch template), respeitando o mínimo saudável, com rollback.'),
  ('saa', 'Arquiteturas Resilientes', 'Escalar workers de fila', 'Target tracking na métrica backlog por instância = mensagens visíveis ÷ instâncias, com alvo = latência aceitável ÷ tempo por mensagem.'),
  ('saa', 'Arquiteturas de Alta Performance', 'Lazy loading × write-through', 'Lazy loading: preenche o cache no miss; pode servir dado velho até o TTL. Write-through: atualiza o cache em toda escrita; nunca desatualiza, mas grava mais.'),
  ('saa', 'Arquiteturas de Alta Performance', 'Limites do S3 por prefixo', '≥ 3.500 PUT/COPY/POST/DELETE e 5.500 GET/HEAD por segundo POR prefixo. Mais prefixos = mais throughput.'),
  ('saa', 'Arquiteturas de Alta Performance', 'Multipart upload × byte-range fetch', 'Multipart: envia partes em paralelo (recomendado acima de 100 MB, obrigatório acima de 5 GB). Byte-range: baixa faixas do objeto em paralelo.'),
  ('saa', 'Arquiteturas de Alta Performance', 'gp3 × io2 × st1 × sc1', 'gp3: SSD geral, IOPS independentes do tamanho. io2 Block Express: IOPS altíssimos, sub-ms. st1: HDD de throughput sequencial. sc1: HDD frio, o mais barato.'),
  ('saa', 'Arquiteturas de Alta Performance', 'EFS: modos de throughput', 'Elastic: escala sozinho com a carga (padrão recomendado). Provisioned: valor fixo contratado. Bursting: cresce com o tamanho armazenado.'),
  ('saa', 'Arquiteturas de Alta Performance', 'FSx for Lustre + S3', 'Vincula um bucket S3 e apresenta os objetos como arquivos com centenas de GB/s, para HPC e treinamento de ML.'),
  ('saa', 'Arquiteturas de Alta Performance', 'EFA × ENA', 'ENA: rede aprimorada padrão, até centenas de Gbps. EFA: ENA + bypass do SO para MPI/NCCL, latência baixa e consistente em HPC.'),
  ('saa', 'Arquiteturas de Alta Performance', 'Global Accelerator × CloudFront', 'Global Accelerator: 2 IPs anycast, TCP/UDP pela rede da AWS, sem cache, failover rápido. CloudFront: CDN HTTP com cache na borda.'),
  ('saa', 'Arquiteturas de Alta Performance', 'Route 53: latência × geolocalização × geoproximidade', 'Latência: Região mais rápida para o usuário. Geolocalização: pelo país ou continente do usuário. Geoproximidade: pela distância, com ajuste de viés.'),
  ('saa', 'Arquiteturas de Alta Performance', 'Lambda: memória = CPU', 'A CPU é proporcional à memória (128 MB a 10.240 MB). Função lenta por CPU? Aumente a memória.'),
  ('saa', 'Arquiteturas de Alta Performance', 'Tipos de escalonamento do ASG', 'Target tracking: mantém a métrica no alvo. Step: degraus por alarme. Scheduled: horários conhecidos. Predictive: ML prevê picos recorrentes.'),
  ('saa', 'Arquiteturas de Alta Performance', 'Warm pools', 'Instâncias já inicializadas e paradas, prontas para entrar no ASG em segundos. Para apps com boot longo; paradas pagam só o armazenamento.'),
  ('saa', 'Arquiteturas de Alta Performance', 'CloudFront Functions × Lambda@Edge', 'Functions: JS leve, sub-ms, milhões de req/s (cabeçalhos, URLs). Lambda@Edge: lógica mais pesada, chamadas de rede, acesso ao corpo.'),
  ('saa', 'Arquiteturas de Alta Performance', 'Kinesis: shards e fan-out', 'Shard: 1 MB/s ou 1.000 registros/s de escrita, 2 MB/s de leitura compartilhada. Enhanced fan-out: 2 MB/s por shard POR consumidor.'),
  ('saa', 'Arquiteturas de Alta Performance', 'Redshift Spectrum × Athena', 'Spectrum: o Redshift consulta dados no S3 e junta com tabelas do cluster. Athena: SQL serverless independente sobre o S3.'),
  ('saa', 'Arquiteturas de Alta Performance', 'DynamoDB on-demand × provisionado', 'On-demand: tráfego imprevisível, paga por requisição. Provisionado + Auto Scaling: tráfego previsível, mais barato (e aceita capacidade reservada).'),
  ('saa', 'Arquiteturas com Custo Otimizado', 'Glacier Instant × Flexible × Deep Archive', 'Instant: ms, acesso trimestral. Flexible: minutos a 12 h (bulk grátis). Deep Archive: até 12 h (bulk até 48 h), o mais barato. Mínimos: 90/90/180 dias.'),
  ('saa', 'Arquiteturas com Custo Otimizado', 'Graviton', 'Instâncias ARM da AWS: até 40% melhor preço por desempenho que x86 comparáveis. Java, Python, Node e contêineres multi-arch migram fácil.'),
  ('saa', 'Arquiteturas com Custo Otimizado', 'Spot sem sustos', 'Diversifique tipos e AZs e use a estratégia price-capacity-optimized. Aviso de 2 minutos antes da interrupção; salve checkpoints.'),
  ('saa', 'Arquiteturas com Custo Otimizado', 'gp2 → gp3', '~20% mais barato por GB, 3.000 IOPS e 125 MB/s de base em qualquer tamanho. Migração online com Elastic Volumes.'),
  ('saa', 'Arquiteturas com Custo Otimizado', 'EBS Snapshots Archive', 'Até 75% mais barato para snapshots guardados por muito tempo e raramente restaurados. Mínimo de 90 dias; restauração em até 72 h.'),
  ('saa', 'Arquiteturas com Custo Otimizado', 'Tráfego entre AZs', 'Cobrado por GB em cada direção. Considere-o ao desenhar arquiteturas com muito tráfego entre camadas em AZs diferentes.'),
  ('saa', 'Arquiteturas com Custo Otimizado', 'S3 Storage Lens', 'Visão de uso e atividade do S3 em toda a organização, com recomendações de custo (ex: buckets sem regra de ciclo de vida).'),
  ('saa', 'Arquiteturas com Custo Otimizado', 'Budgets actions', 'Ao atingir o limite, o AWS Budgets pode aplicar política IAM ou SCP ou parar instâncias EC2 e RDS automaticamente.'),
  ('saa', 'Arquiteturas com Custo Otimizado', 'Fargate Spot', 'Tarefas ECS interrompíveis com grande desconto sobre o Fargate, com aviso de 2 minutos. Misture com Fargate comum nos capacity providers.'),
  ('saa', 'Arquiteturas com Custo Otimizado', 'SQS long polling', 'WaitTimeSeconds até 20 s: menos respostas vazias, menos requisições cobradas e menor latência para receber mensagens.'),
  ('saa', 'Arquiteturas com Custo Otimizado', 'CloudWatch Logs: retenção', 'Por padrão, os logs NUNCA expiram. Defina a retenção por grupo e exporte para o S3 o que precisa ser arquivado.'),
  ('saa', 'Arquiteturas com Custo Otimizado', 'DynamoDB TTL', 'Apaga itens expirados automaticamente, sem consumir capacidade de escrita e sem custo extra.'),
  ('saa', 'Arquiteturas com Custo Otimizado', 'S3 Requester Pays', 'Quem baixa paga as requisições e a transferência; o dono do bucket paga só o armazenamento. Ideal para datasets compartilhados.'),
  ('saa', 'Arquiteturas com Custo Otimizado', 'Redshift Serverless', 'Sem cluster para dimensionar: escala sozinho e cobra só enquanto há consultas. Ideal para análises intermitentes.'),
  ('saa', 'Arquiteturas com Custo Otimizado', 'Athena mais barato', 'Converta para Parquet ou ORC compactado e particione (ex: por data): o Athena cobra por dado lido.'),
  ('aif', 'Fundamentos de IA e ML', 'IA ⊃ ML ⊃ deep learning', 'IA: sistemas que fazem tarefas ''inteligentes''. ML: aprende padrões com dados. Deep learning: ML com redes neurais de muitas camadas.'),
  ('aif', 'Fundamentos de IA e ML', 'Supervisionado × não supervisionado × reforço', 'Supervisionado: dados rotulados (classificação, regressão). Não supervisionado: sem rótulos (clusters, anomalias). Reforço: agente aprende com recompensas.'),
  ('aif', 'Fundamentos de IA e ML', 'Clusterização', 'Agrupa dados semelhantes sem rótulos prévios (ex: k-means para segmentar clientes). É aprendizado não supervisionado.'),
  ('aif', 'Fundamentos de IA e ML', 'Underfitting', 'Ruim no treino E no teste: modelo simples demais (alto viés). Use um modelo mais capaz ou features melhores.'),
  ('aif', 'Fundamentos de IA e ML', 'Viés × variância', 'Alto viés: suposições simples demais, underfitting. Alta variância: sensível demais ao treino, overfitting. O objetivo é equilibrar.'),
  ('aif', 'Fundamentos de IA e ML', 'Parâmetro × hiperparâmetro', 'Parâmetro: aprendido no treino (pesos, coeficientes). Hiperparâmetro: definido antes (learning rate, épocas, profundidade).'),
  ('aif', 'Fundamentos de IA e ML', 'F1-score', 'Média harmônica de precisão e recall. Útil com classes desbalanceadas, quando a acurácia engana.'),
  ('aif', 'Fundamentos de IA e ML', 'AUC-ROC', 'Área sob a curva ROC: capacidade de separar as classes em todos os limiares. 1 = perfeito; 0,5 = aleatório.'),
  ('aif', 'Fundamentos de IA e ML', 'Métricas de regressão', 'MAE: erro absoluto médio. RMSE: penaliza mais os erros grandes. R²: proporção da variância explicada.'),
  ('aif', 'Fundamentos de IA e ML', 'Matriz de confusão', 'VP e VN: acertos. FP: previu positivo e era negativo (alarme falso). FN: previu negativo e era positivo (deixou passar).'),
  ('aif', 'Fundamentos de IA e ML', 'Inferência no SageMaker AI', 'Tempo real: baixa latência, sempre ligado. Serverless: tráfego intermitente. Assíncrona: payload grande e processamento longo, escala a zero. Lote: grandes volumes offline.'),
  ('aif', 'Fundamentos de IA e ML', 'Ciclo de vida de ML', 'Problema de negócio → coleta e preparo dos dados → features → treino e ajuste → avaliação → implantação → monitoramento (e retreino).'),
  ('aif', 'Fundamentos de IA e ML', 'SageMaker: quem faz o quê (1)', 'Ground Truth: rotulagem. Canvas: ML sem código. Feature Store: features reutilizáveis. JumpStart: modelos pré-treinados prontos.'),
  ('aif', 'Fundamentos de IA e ML', 'SageMaker: quem faz o quê (2)', 'Pipelines: MLOps. Model Registry: versões e aprovação. Model Monitor: drift em produção. Clarify: viés e explicabilidade.'),
  ('aif', 'Fundamentos de IA e ML', 'Quando NÃO usar ML', 'Quando uma regra determinística resolve com exatidão, faltam dados de qualidade ou o erro probabilístico é inaceitável.'),
  ('aif', 'Fundamentos de IA Generativa', 'Transformer e autoatenção', 'A autoatenção pondera a relação de cada token com todos os outros, capturando contexto de longo alcance e permitindo paralelismo.'),
  ('aif', 'Fundamentos de IA Generativa', 'Pré-treinamento de LLM', 'Auto-supervisionado: prever o próximo token em enormes volumes de texto não rotulado. É a etapa mais cara do ciclo.'),
  ('aif', 'Fundamentos de IA Generativa', 'Modelo multimodal', 'Entende ou gera mais de um tipo de dado: texto, imagem, áudio, vídeo.'),
  ('aif', 'Fundamentos de IA Generativa', 'Modelo de difusão', 'Gera imagens partindo de ruído e removendo-o passo a passo, guiado pelo prompt.'),
  ('aif', 'Fundamentos de IA Generativa', 'GAN', 'Gerador cria dados sintéticos; discriminador tenta separar falsos de reais. A competição melhora o gerador.'),
  ('aif', 'Fundamentos de IA Generativa', 'Janela de contexto', 'Máximo de tokens (prompt + histórico + contexto + resposta) que o modelo considera de uma vez.'),
  ('aif', 'Fundamentos de IA Generativa', 'Chunking', 'Dividir documentos em trechos de tamanho adequado, com sobreposição, antes de gerar embeddings para RAG.'),
  ('aif', 'Fundamentos de IA Generativa', 'Banco vetorial', 'Armazena embeddings e encontra os mais semelhantes a uma consulta (busca semântica). Base do RAG.'),
  ('aif', 'Fundamentos de IA Generativa', 'Similaridade de cosseno', 'Mede o ângulo entre dois vetores: quanto mais próximo de 1, mais parecidos os significados.'),
  ('aif', 'Fundamentos de IA Generativa', 'Data de corte de conhecimento', 'O modelo só sabe o que estava nos dados até o fim do treino. Para dados recentes: RAG ou ferramentas.'),
  ('aif', 'Fundamentos de IA Generativa', 'Não determinismo', 'O mesmo prompt pode gerar respostas diferentes porque o modelo amostra tokens. Temperature baixa reduz a variação.'),
  ('aif', 'Fundamentos de IA Generativa', 'Bedrock: formas de pagar', 'Sob demanda: por token de entrada e de saída. Lote: mais barato, assíncrono. Provisioned Throughput: capacidade reservada (e para modelos customizados).'),
  ('aif', 'Fundamentos de IA Generativa', 'Amazon Q Developer × Q Business', 'Q Developer: assistente de código na IDE e no console. Q Business: assistente corporativo sobre os dados da empresa, respeitando permissões.'),
  ('aif', 'Fundamentos de IA Generativa', 'PartyRock', 'Playground do Bedrock para criar apps de IA generativa sem código, para aprender e prototipar.'),
  ('aif', 'Fundamentos de IA Generativa', 'Ciclo de vida de um modelo de fundação', 'Seleção de dados → pré-treinamento → ajuste (fine-tuning) → avaliação → implantação → feedback.'),
  ('aif', 'Aplicações de Modelos de Fundação', 'top_p × top_k', 'top_p: considera os tokens até somar a probabilidade p (núcleo). top_k: considera só os k mais prováveis. Valores baixos = saída mais focada.'),
  ('aif', 'Aplicações de Modelos de Fundação', 'max tokens × stop sequences', 'Max tokens: limite de tamanho da resposta (resposta cortada? aumente). Stop sequence: texto que encerra a geração.'),
  ('aif', 'Aplicações de Modelos de Fundação', 'Zero-shot × few-shot', 'Zero-shot: só a instrução. Few-shot: alguns exemplos no prompt mostram o padrão. Nenhum dos dois altera pesos.'),
  ('aif', 'Aplicações de Modelos de Fundação', 'Chain-of-thought', 'Pedir raciocínio passo a passo antes da resposta final; melhora problemas de lógica e várias etapas.'),
  ('aif', 'Aplicações de Modelos de Fundação', 'Custo de adaptar um modelo', 'Do mais barato ao mais caro: prompt → RAG → fine-tuning → pré-treinamento contínuo → pré-treinar do zero.'),
  ('aif', 'Aplicações de Modelos de Fundação', 'Fine-tuning × pré-treinamento contínuo', 'Fine-tuning: pares rotulados de entrada e saída (formato, tarefa). Pré-treinamento contínuo: muito texto do domínio SEM rótulo (vocabulário).'),
  ('aif', 'Aplicações de Modelos de Fundação', 'Destilação', 'Um modelo grande (professor) gera exemplos para treinar um menor (aluno), mais barato e rápido na mesma tarefa.'),
  ('aif', 'Aplicações de Modelos de Fundação', 'Instruction tuning', 'Fine-tuning com instruções e respostas para o modelo seguir comandos em linguagem natural.'),
  ('aif', 'Aplicações de Modelos de Fundação', 'RLHF', 'Humanos comparam respostas → modelo de recompensa → o LLM é otimizado para as preferências humanas.'),
  ('aif', 'Aplicações de Modelos de Fundação', 'ROUGE × BLEU × BERTScore', 'ROUGE: resumos (sobreposição, recall). BLEU: tradução (n-gramas, precisão). BERTScore: similaridade semântica via embeddings.'),
  ('aif', 'Aplicações de Modelos de Fundação', 'Knowledge Bases do Bedrock', 'Sincroniza fontes (ex: S3) → chunking → embeddings → banco vetorial. Na consulta: recupera trechos e gera a resposta com citações.'),
  ('aif', 'Aplicações de Modelos de Fundação', 'Bancos vetoriais na AWS', 'OpenSearch Service/Serverless, Aurora PostgreSQL e RDS com pgvector, Neptune Analytics, MemoryDB e DocumentDB.'),
  ('aif', 'Aplicações de Modelos de Fundação', 'Reranking', 'Segunda etapa que reordena os trechos recuperados por relevância real para a pergunta antes de enviá-los ao modelo.'),
  ('aif', 'Aplicações de Modelos de Fundação', 'Busca híbrida', 'Palavra-chave + semântica. Resolve códigos, siglas e nomes exatos que embeddings sozinhos podem perder.'),
  ('aif', 'Aplicações de Modelos de Fundação', 'Tool use (function calling)', 'O modelo recebe a descrição das ferramentas e devolve uma chamada estruturada; a aplicação executa e devolve o resultado.'),
  ('aif', 'Aplicações de Modelos de Fundação', 'Prompt caching', 'Reaproveita o processamento de prefixos repetidos (prompt de sistema longo, documentos): menos custo e menor latência.'),
  ('aif', 'Aplicações de Modelos de Fundação', 'Bedrock Agents: action group', 'Define ações (via OpenAPI ou esquema de funções) que o agente pode chamar; a execução costuma ser uma Lambda.'),
  ('aif', 'Aplicações de Modelos de Fundação', 'Jailbreak × prompt leaking', 'Jailbreak: burlar as regras do modelo. Prompt leaking: fazer o modelo revelar o prompt de sistema ou dados internos.'),
  ('aif', 'Aplicações de Modelos de Fundação', 'Bedrock Model Evaluation', 'Compara modelos com métricas automáticas, LLM como juiz ou avaliação humana, usando seus próprios prompts.'),
  ('aif', 'Diretrizes para IA Responsável', 'Dimensões da IA responsável (AWS)', 'Equidade, explicabilidade, privacidade e segurança, proteção (safety), controlabilidade, veracidade e robustez, governança e transparência.'),
  ('aif', 'Diretrizes para IA Responsável', 'SageMaker Clarify', 'Mede viés nos dados (antes do treino) e nas previsões (depois) e explica previsões com valores SHAP.'),
  ('aif', 'Diretrizes para IA Responsável', 'Bedrock Guardrails: peças', 'Filtros de conteúdo, tópicos negados, filtro de palavras, filtro de informações sensíveis (PII), fundamentação contextual e raciocínio automatizado.'),
  ('aif', 'Diretrizes para IA Responsável', 'Fundamentação contextual', 'Guardrail que bloqueia respostas sem apoio nos documentos recuperados ou irrelevantes para a pergunta.'),
  ('aif', 'Diretrizes para IA Responsável', 'Amazon A2I', 'Revisão humana acionada por regras, como baixa confiança, para previsões do Textract, do Rekognition ou de modelos próprios.'),
  ('aif', 'Diretrizes para IA Responsável', 'AWS AI Service Cards', 'Documentos de transparência da AWS sobre uso pretendido, limitações e boas práticas de cada serviço de IA.'),
  ('aif', 'Diretrizes para IA Responsável', 'Interpretável × opaco', 'Interpretável (regressão, árvore): fácil explicar, às vezes menos preciso. Opaco (deep learning, LLM): mais capaz, difícil de explicar.'),
  ('aif', 'Diretrizes para IA Responsável', 'Riscos legais da IA generativa', 'Propriedade intelectual, resultados enviesados, alucinações usadas como fato, exposição de dados e perda de confiança do cliente.'),
  ('aif', 'Diretrizes para IA Responsável', 'Robustez', 'Manter desempenho confiável com dados ruidosos, fora do padrão ou adversariais.'),
  ('aif', 'Diretrizes para IA Responsável', 'Sub-representação nos dados', 'Grupos pouco presentes no treino recebem previsões piores. Avalie por subgrupo e balanceie ou complemente os dados.'),
  ('aif', 'Segurança, Conformidade e Governança para Soluções de IA', 'Bedrock e os seus dados', 'Prompts e respostas não treinam os modelos base nem vão para os fornecedores. Criptografia em trânsito e em repouso, com KMS opcional.'),
  ('aif', 'Segurança, Conformidade e Governança para Soluções de IA', 'Generative AI Security Scoping Matrix', '1: app de consumo. 2: app corporativo. 3: modelo pré-treinado via API. 4: modelo ajustado. 5: modelo próprio. Quanto maior, mais responsabilidade sua.'),
  ('aif', 'Segurança, Conformidade e Governança para Soluções de IA', 'Invocation logging × CloudTrail', 'Model invocation logging: conteúdo dos prompts e respostas (CloudWatch/S3). CloudTrail: quem chamou qual API e quando.'),
  ('aif', 'Segurança, Conformidade e Governança para Soluções de IA', 'Bedrock sem internet', 'VPC endpoint de interface (PrivateLink) para o Bedrock: o tráfego fica na rede da AWS.'),
  ('aif', 'Segurança, Conformidade e Governança para Soluções de IA', 'Data poisoning', 'Exemplos maliciosos inseridos nos dados de treino ou de fine-tuning. Defesa: origem controlada, curadoria e validação.'),
  ('aif', 'Segurança, Conformidade e Governança para Soluções de IA', 'ISO/IEC 42001', 'Norma de sistema de gestão de IA (uso responsável e governança). A AWS é certificada.'),
  ('aif', 'Segurança, Conformidade e Governança para Soluções de IA', 'EU AI Act', 'Regulação europeia baseada em risco: inaceitável (proibido), alto (requisitos rígidos), limitado (transparência), mínimo.'),
  ('aif', 'Segurança, Conformidade e Governança para Soluções de IA', 'Audit Manager para IA generativa', 'Framework pronto de boas práticas de IA generativa, com coleta contínua de evidências para auditoria.'),
  ('aif', 'Segurança, Conformidade e Governança para Soluções de IA', 'Anonimização × pseudonimização', 'Anonimização: remove a identidade de forma irreversível. Pseudonimização: troca identificadores por códigos, reversível com uma chave guardada à parte.'),
  ('aif', 'Segurança, Conformidade e Governança para Soluções de IA', 'Responsabilidade compartilhada no Bedrock', 'AWS: infraestrutura e serviço. Cliente: IAM, dados, configuração, guardrails, avaliação e uso responsável da aplicação.');
